/* This file was automatically generated by CasADi 3.6.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) thd_bias_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};

/* thd_bias:(i0[2],i1[2],i2[2],i3[2])->(o0[4],o1[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=6.;
  a1=1.6000000000000001e-03;
  a2=8.;
  a3=arg[0]? arg[0][0] : 0;
  a3=(a3/a0);
  a4=cos(a3);
  a4=(a2*a4);
  a5=arg[1]? arg[1][1] : 0;
  a6=sin(a5);
  a7=(a4*a6);
  a7=(a1*a7);
  a8=4.0000000000000002e-04;
  a9=57.;
  a10=arg[1]? arg[1][0] : 0;
  a11=cos(a10);
  a11=(a9*a11);
  a12=cos(a5);
  a13=(a11*a12);
  a13=(a8*a13);
  a7=(a7-a13);
  a13=7.;
  a14=sin(a10);
  a14=(a13*a14);
  a15=cos(a5);
  a16=(a14*a15);
  a16=(a1*a16);
  a7=(a7+a16);
  a16=cos(a10);
  a16=(a2*a16);
  a17=sin(a3);
  a18=(a16*a17);
  a19=cos(a5);
  a20=(a18*a19);
  a20=(a1*a20);
  a7=(a7-a20);
  a20=2.0000000000000001e-04;
  a21=49.;
  a22=sin(a10);
  a22=(a21*a22);
  a22=(a20*a22);
  a23=5.0000000000000002e-05;
  a24=399.;
  a25=cos(a10);
  a25=(a24*a25);
  a25=(a23*a25);
  a22=(a22-a25);
  a25=sin(a5);
  a26=sin(a10);
  a26=(a9*a26);
  a27=(a25*a26);
  a27=(a8*a27);
  a22=(a22+a27);
  a27=sin(a3);
  a27=(a13*a27);
  a28=cos(a10);
  a29=(a27*a28);
  a29=(a1*a29);
  a22=(a22-a29);
  a29=sin(a5);
  a30=cos(a10);
  a30=(a13*a30);
  a31=(a29*a30);
  a31=(a1*a31);
  a22=(a22+a31);
  a31=sin(a5);
  a32=sin(a10);
  a32=(a2*a32);
  a33=(a17*a32);
  a34=(a31*a33);
  a34=(a1*a34);
  a22=(a22+a34);
  a34=arg[0]? arg[0][1] : 0;
  a34=(a34/a0);
  a35=cos(a34);
  a35=(a2*a35);
  a36=sin(a5);
  a37=(a35*a36);
  a37=(a1*a37);
  a38=cos(a10);
  a38=(a9*a38);
  a39=cos(a5);
  a40=(a38*a39);
  a40=(a8*a40);
  a37=(a37-a40);
  a40=sin(a10);
  a40=(a13*a40);
  a41=cos(a5);
  a42=(a40*a41);
  a42=(a1*a42);
  a37=(a37-a42);
  a42=cos(a10);
  a42=(a2*a42);
  a43=sin(a34);
  a44=(a42*a43);
  a45=cos(a5);
  a46=(a44*a45);
  a46=(a1*a46);
  a37=(a37-a46);
  a46=(a22*a37);
  a47=sin(a10);
  a47=(a21*a47);
  a47=(a20*a47);
  a48=cos(a10);
  a48=(a24*a48);
  a48=(a23*a48);
  a47=(a47+a48);
  a48=sin(a5);
  a49=sin(a10);
  a49=(a9*a49);
  a50=(a48*a49);
  a50=(a8*a50);
  a47=(a47+a50);
  a50=sin(a34);
  a50=(a13*a50);
  a51=cos(a10);
  a52=(a50*a51);
  a52=(a1*a52);
  a47=(a47+a52);
  a52=sin(a5);
  a53=cos(a10);
  a53=(a13*a53);
  a54=(a52*a53);
  a54=(a1*a54);
  a47=(a47-a54);
  a54=sin(a5);
  a55=sin(a10);
  a55=(a2*a55);
  a56=(a43*a55);
  a57=(a54*a56);
  a57=(a1*a57);
  a47=(a47+a57);
  a57=(a7*a47);
  a46=(a46-a57);
  a57=(a7/a46);
  a58=cos(a5);
  a59=1.6666666666666666e-01;
  a60=cos(a34);
  a61=arg[2]? arg[2][1] : 0;
  a62=(a59*a61);
  a60=(a60*a62);
  a60=(a59*a60);
  a60=(a2*a60);
  a60=(a58*a60);
  a60=(a1*a60);
  a63=sin(a34);
  a63=(a63*a62);
  a63=(a59*a63);
  a63=(a9*a63);
  a63=(a8*a63);
  a60=(a60-a63);
  a63=sin(a10);
  a64=sin(a34);
  a64=(a64*a62);
  a64=(a59*a64);
  a64=(a13*a64);
  a64=(a63*a64);
  a64=(a1*a64);
  a60=(a60-a64);
  a64=sin(a34);
  a64=(a64*a62);
  a64=(a59*a64);
  a64=(a42*a64);
  a64=(a54*a64);
  a64=(a1*a64);
  a60=(a60+a64);
  a64=(a57*a60);
  a65=cos(a34);
  a65=(a59*a65);
  a65=(a9*a65);
  a65=(a8*a65);
  a66=sin(a34);
  a66=(a59*a66);
  a66=(a2*a66);
  a67=(a58*a66);
  a67=(a1*a67);
  a65=(a65+a67);
  a67=cos(a34);
  a67=(a59*a67);
  a67=(a13*a67);
  a68=(a63*a67);
  a68=(a1*a68);
  a65=(a65+a68);
  a68=cos(a34);
  a68=(a59*a68);
  a69=(a42*a68);
  a70=(a54*a69);
  a70=(a1*a70);
  a65=(a65-a70);
  a70=sin(a3);
  a71=arg[2]? arg[2][0] : 0;
  a72=(a59*a71);
  a70=(a70*a72);
  a70=(a2*a70);
  a70=(a6*a70);
  a70=(a1*a70);
  a73=cos(a3);
  a73=(a73*a72);
  a74=(a16*a73);
  a74=(a19*a74);
  a74=(a1*a74);
  a70=(a70+a74);
  a74=(a70/a46);
  a75=(a57/a46);
  a73=(a32*a73);
  a73=(a31*a73);
  a73=(a1*a73);
  a76=cos(a3);
  a76=(a76*a72);
  a76=(a13*a76);
  a76=(a28*a76);
  a76=(a1*a76);
  a73=(a73-a76);
  a76=(a37*a73);
  a77=sin(a34);
  a77=(a77*a62);
  a77=(a2*a77);
  a77=(a36*a77);
  a77=(a1*a77);
  a78=cos(a34);
  a78=(a78*a62);
  a79=(a42*a78);
  a79=(a45*a79);
  a79=(a1*a79);
  a77=(a77+a79);
  a79=(a22*a77);
  a76=(a76-a79);
  a79=cos(a34);
  a79=(a79*a62);
  a79=(a13*a79);
  a79=(a51*a79);
  a79=(a1*a79);
  a78=(a55*a78);
  a78=(a54*a78);
  a78=(a1*a78);
  a79=(a79+a78);
  a78=(a7*a79);
  a70=(a47*a70);
  a78=(a78-a70);
  a76=(a76-a78);
  a75=(a75*a76);
  a74=(a74+a75);
  a74=(a65*a74);
  a64=(a64-a74);
  a64=(a0*a64);
  a74=cos(a5);
  a75=arg[3]? arg[3][1] : 0;
  a74=(a74*a75);
  a74=(a4*a74);
  a74=(a1*a74);
  a78=sin(a10);
  a70=arg[3]? arg[3][0] : 0;
  a78=(a78*a70);
  a78=(a9*a78);
  a78=(a12*a78);
  a62=sin(a5);
  a62=(a62*a75);
  a62=(a11*a62);
  a78=(a78+a62);
  a78=(a8*a78);
  a74=(a74+a78);
  a78=cos(a10);
  a78=(a78*a70);
  a78=(a13*a78);
  a78=(a15*a78);
  a62=sin(a5);
  a62=(a62*a75);
  a62=(a14*a62);
  a78=(a78-a62);
  a78=(a1*a78);
  a74=(a74+a78);
  a78=sin(a10);
  a78=(a78*a70);
  a78=(a2*a78);
  a62=(a17*a78);
  a62=(a19*a62);
  a80=sin(a5);
  a80=(a80*a75);
  a80=(a18*a80);
  a62=(a62+a80);
  a62=(a1*a62);
  a74=(a74+a62);
  a62=(a74/a46);
  a80=(a57/a46);
  a81=cos(a10);
  a81=(a81*a70);
  a81=(a21*a81);
  a81=(a20*a81);
  a82=sin(a10);
  a82=(a82*a70);
  a82=(a24*a82);
  a82=(a23*a82);
  a81=(a81+a82);
  a82=cos(a5);
  a82=(a82*a75);
  a82=(a26*a82);
  a83=cos(a10);
  a83=(a83*a70);
  a83=(a9*a83);
  a83=(a25*a83);
  a82=(a82+a83);
  a82=(a8*a82);
  a81=(a81+a82);
  a82=sin(a10);
  a82=(a82*a70);
  a82=(a27*a82);
  a82=(a1*a82);
  a81=(a81+a82);
  a82=cos(a5);
  a82=(a82*a75);
  a82=(a30*a82);
  a83=sin(a10);
  a83=(a83*a70);
  a83=(a13*a83);
  a83=(a29*a83);
  a82=(a82-a83);
  a82=(a1*a82);
  a81=(a81+a82);
  a82=cos(a5);
  a82=(a82*a75);
  a83=(a33*a82);
  a84=cos(a10);
  a84=(a84*a70);
  a84=(a2*a84);
  a84=(a17*a84);
  a84=(a31*a84);
  a83=(a83+a84);
  a83=(a1*a83);
  a81=(a81+a83);
  a83=(a37*a81);
  a84=cos(a5);
  a84=(a84*a75);
  a84=(a35*a84);
  a84=(a1*a84);
  a85=sin(a10);
  a85=(a85*a70);
  a85=(a9*a85);
  a85=(a39*a85);
  a86=sin(a5);
  a86=(a86*a75);
  a86=(a38*a86);
  a85=(a85+a86);
  a85=(a8*a85);
  a84=(a84+a85);
  a85=cos(a10);
  a85=(a85*a70);
  a85=(a13*a85);
  a85=(a41*a85);
  a86=sin(a5);
  a86=(a86*a75);
  a86=(a40*a86);
  a85=(a85-a86);
  a85=(a1*a85);
  a84=(a84-a85);
  a85=sin(a10);
  a85=(a85*a70);
  a85=(a2*a85);
  a86=(a43*a85);
  a86=(a45*a86);
  a87=sin(a5);
  a87=(a87*a75);
  a87=(a44*a87);
  a86=(a86+a87);
  a86=(a1*a86);
  a84=(a84+a86);
  a86=(a22*a84);
  a83=(a83+a86);
  a74=(a47*a74);
  a86=cos(a10);
  a86=(a86*a70);
  a86=(a21*a86);
  a86=(a20*a86);
  a87=sin(a10);
  a87=(a87*a70);
  a87=(a24*a87);
  a87=(a23*a87);
  a86=(a86-a87);
  a87=cos(a5);
  a87=(a87*a75);
  a87=(a49*a87);
  a88=cos(a10);
  a88=(a88*a70);
  a88=(a9*a88);
  a88=(a48*a88);
  a87=(a87+a88);
  a87=(a8*a87);
  a86=(a86+a87);
  a87=sin(a10);
  a87=(a87*a70);
  a87=(a50*a87);
  a87=(a1*a87);
  a86=(a86-a87);
  a87=cos(a5);
  a87=(a87*a75);
  a87=(a53*a87);
  a88=sin(a10);
  a88=(a88*a70);
  a88=(a13*a88);
  a88=(a52*a88);
  a87=(a87-a88);
  a87=(a1*a87);
  a86=(a86-a87);
  a87=cos(a5);
  a87=(a87*a75);
  a88=(a56*a87);
  a89=cos(a10);
  a89=(a89*a70);
  a89=(a2*a89);
  a89=(a43*a89);
  a89=(a54*a89);
  a88=(a88+a89);
  a88=(a1*a88);
  a86=(a86+a88);
  a88=(a7*a86);
  a74=(a74+a88);
  a83=(a83-a74);
  a80=(a80*a83);
  a62=(a62-a80);
  a62=(a65*a62);
  a80=cos(a10);
  a80=(a80*a70);
  a80=(a67*a80);
  a80=(a1*a80);
  a74=sin(a5);
  a74=(a74*a75);
  a74=(a66*a74);
  a74=(a1*a74);
  a80=(a80-a74);
  a87=(a69*a87);
  a85=(a68*a85);
  a85=(a54*a85);
  a87=(a87-a85);
  a87=(a1*a87);
  a80=(a80-a87);
  a87=(a57*a80);
  a62=(a62+a87);
  a62=(a0*a62);
  a64=(a64+a62);
  a62=(a61/a0);
  a64=(a64*a62);
  a87=(a37/a46);
  a85=cos(a5);
  a74=cos(a3);
  a74=(a74*a72);
  a74=(a59*a74);
  a74=(a2*a74);
  a74=(a85*a74);
  a74=(a1*a74);
  a88=sin(a3);
  a88=(a88*a72);
  a88=(a59*a88);
  a88=(a9*a88);
  a88=(a8*a88);
  a74=(a74-a88);
  a88=sin(a10);
  a89=sin(a3);
  a89=(a89*a72);
  a89=(a59*a89);
  a89=(a13*a89);
  a89=(a88*a89);
  a89=(a1*a89);
  a74=(a74+a89);
  a89=sin(a3);
  a89=(a89*a72);
  a89=(a59*a89);
  a89=(a16*a89);
  a89=(a31*a89);
  a89=(a1*a89);
  a74=(a74+a89);
  a89=(a87*a74);
  a72=cos(a3);
  a72=(a59*a72);
  a72=(a9*a72);
  a72=(a8*a72);
  a90=sin(a3);
  a90=(a59*a90);
  a90=(a2*a90);
  a91=(a85*a90);
  a91=(a1*a91);
  a72=(a72+a91);
  a91=cos(a3);
  a91=(a59*a91);
  a91=(a13*a91);
  a92=(a88*a91);
  a92=(a1*a92);
  a72=(a72-a92);
  a92=cos(a3);
  a92=(a59*a92);
  a93=(a16*a92);
  a94=(a31*a93);
  a94=(a1*a94);
  a72=(a72-a94);
  a77=(a77/a46);
  a94=(a87/a46);
  a94=(a94*a76);
  a77=(a77+a94);
  a77=(a72*a77);
  a89=(a89-a77);
  a89=(a0*a89);
  a84=(a84/a46);
  a77=(a87/a46);
  a77=(a77*a83);
  a84=(a84-a77);
  a84=(a72*a84);
  a77=sin(a5);
  a77=(a77*a75);
  a77=(a90*a77);
  a77=(a1*a77);
  a94=cos(a10);
  a94=(a94*a70);
  a94=(a91*a94);
  a94=(a1*a94);
  a77=(a77+a94);
  a82=(a93*a82);
  a78=(a92*a78);
  a78=(a31*a78);
  a82=(a82-a78);
  a82=(a1*a82);
  a77=(a77+a82);
  a82=(a87*a77);
  a84=(a84-a82);
  a84=(a0*a84);
  a89=(a89+a84);
  a84=(a71/a0);
  a89=(a89*a84);
  a64=(a64-a89);
  if (res[0]!=0) res[0][2]=a64;
  a79=(a79/a46);
  a64=(a47/a46);
  a89=(a64/a46);
  a89=(a89*a76);
  a79=(a79-a89);
  a79=(a72*a79);
  a74=(a64*a74);
  a79=(a79+a74);
  a79=(a0*a79);
  a86=(a86/a46);
  a74=(a64/a46);
  a74=(a74*a83);
  a86=(a86-a74);
  a86=(a72*a86);
  a77=(a64*a77);
  a86=(a86-a77);
  a86=(a0*a86);
  a79=(a79+a86);
  a79=(a79*a84);
  a73=(a73/a46);
  a84=(a22/a46);
  a86=(a84/a46);
  a86=(a86*a76);
  a73=(a73-a86);
  a73=(a65*a73);
  a60=(a84*a60);
  a73=(a73+a60);
  a73=(a0*a73);
  a81=(a81/a46);
  a60=(a84/a46);
  a60=(a60*a83);
  a81=(a81-a60);
  a81=(a65*a81);
  a80=(a84*a80);
  a81=(a81+a80);
  a0=(a0*a81);
  a73=(a73+a0);
  a73=(a73*a62);
  a79=(a79-a73);
  if (res[0]!=0) res[0][3]=a79;
  a79=cos(a5);
  a79=(a79*a75);
  a35=(a35*a79);
  a79=sin(a34);
  a73=(a59*a61);
  a79=(a79*a73);
  a79=(a2*a79);
  a36=(a36*a79);
  a35=(a35-a36);
  a35=(a1*a35);
  a36=sin(a10);
  a36=(a36*a70);
  a36=(a9*a36);
  a39=(a39*a36);
  a36=sin(a5);
  a36=(a36*a75);
  a38=(a38*a36);
  a39=(a39+a38);
  a39=(a8*a39);
  a35=(a35+a39);
  a39=cos(a10);
  a39=(a39*a70);
  a39=(a13*a39);
  a41=(a41*a39);
  a39=sin(a5);
  a39=(a39*a75);
  a40=(a40*a39);
  a41=(a41-a40);
  a41=(a1*a41);
  a35=(a35-a41);
  a41=cos(a34);
  a41=(a41*a73);
  a40=(a42*a41);
  a39=sin(a10);
  a39=(a39*a70);
  a39=(a2*a39);
  a38=(a43*a39);
  a40=(a40-a38);
  a45=(a45*a40);
  a40=sin(a5);
  a40=(a40*a75);
  a44=(a44*a40);
  a45=(a45-a44);
  a45=(a1*a45);
  a35=(a35-a45);
  a45=(a35/a46);
  a44=(a87/a46);
  a40=cos(a10);
  a40=(a40*a70);
  a40=(a21*a40);
  a40=(a20*a40);
  a38=sin(a10);
  a38=(a38*a70);
  a38=(a24*a38);
  a38=(a23*a38);
  a40=(a40+a38);
  a38=cos(a5);
  a38=(a38*a75);
  a26=(a26*a38);
  a38=cos(a10);
  a38=(a38*a70);
  a38=(a9*a38);
  a25=(a25*a38);
  a26=(a26+a25);
  a26=(a8*a26);
  a40=(a40+a26);
  a26=cos(a3);
  a25=(a59*a71);
  a26=(a26*a25);
  a26=(a13*a26);
  a28=(a28*a26);
  a26=sin(a10);
  a26=(a26*a70);
  a27=(a27*a26);
  a28=(a28-a27);
  a28=(a1*a28);
  a40=(a40-a28);
  a28=cos(a5);
  a28=(a28*a75);
  a30=(a30*a28);
  a28=sin(a10);
  a28=(a28*a70);
  a28=(a13*a28);
  a29=(a29*a28);
  a30=(a30-a29);
  a30=(a1*a30);
  a40=(a40+a30);
  a30=cos(a5);
  a30=(a30*a75);
  a33=(a33*a30);
  a29=cos(a3);
  a29=(a29*a25);
  a32=(a32*a29);
  a28=cos(a10);
  a28=(a28*a70);
  a28=(a2*a28);
  a28=(a17*a28);
  a32=(a32+a28);
  a32=(a31*a32);
  a33=(a33+a32);
  a33=(a1*a33);
  a40=(a40+a33);
  a37=(a37*a40);
  a22=(a22*a35);
  a37=(a37+a22);
  a22=cos(a5);
  a22=(a22*a75);
  a4=(a4*a22);
  a22=sin(a3);
  a22=(a22*a25);
  a22=(a2*a22);
  a6=(a6*a22);
  a4=(a4-a6);
  a4=(a1*a4);
  a6=sin(a10);
  a6=(a6*a70);
  a6=(a9*a6);
  a12=(a12*a6);
  a6=sin(a5);
  a6=(a6*a75);
  a11=(a11*a6);
  a12=(a12+a11);
  a12=(a8*a12);
  a4=(a4+a12);
  a12=cos(a10);
  a12=(a12*a70);
  a12=(a13*a12);
  a15=(a15*a12);
  a12=sin(a5);
  a12=(a12*a75);
  a14=(a14*a12);
  a15=(a15-a14);
  a15=(a1*a15);
  a4=(a4+a15);
  a29=(a16*a29);
  a15=sin(a10);
  a15=(a15*a70);
  a15=(a2*a15);
  a17=(a17*a15);
  a29=(a29-a17);
  a19=(a19*a29);
  a29=sin(a5);
  a29=(a29*a75);
  a18=(a18*a29);
  a19=(a19-a18);
  a19=(a1*a19);
  a4=(a4-a19);
  a47=(a47*a4);
  a19=cos(a10);
  a19=(a19*a70);
  a21=(a21*a19);
  a20=(a20*a21);
  a21=sin(a10);
  a21=(a21*a70);
  a24=(a24*a21);
  a23=(a23*a24);
  a20=(a20-a23);
  a23=cos(a5);
  a23=(a23*a75);
  a49=(a49*a23);
  a23=cos(a10);
  a23=(a23*a70);
  a23=(a9*a23);
  a48=(a48*a23);
  a49=(a49+a48);
  a49=(a8*a49);
  a20=(a20+a49);
  a49=cos(a34);
  a49=(a49*a73);
  a49=(a13*a49);
  a51=(a51*a49);
  a49=sin(a10);
  a49=(a49*a70);
  a50=(a50*a49);
  a51=(a51-a50);
  a51=(a1*a51);
  a20=(a20+a51);
  a51=cos(a5);
  a51=(a51*a75);
  a53=(a53*a51);
  a51=sin(a10);
  a51=(a51*a70);
  a51=(a13*a51);
  a52=(a52*a51);
  a53=(a53-a52);
  a53=(a1*a53);
  a20=(a20-a53);
  a53=cos(a5);
  a53=(a53*a75);
  a56=(a56*a53);
  a55=(a55*a41);
  a41=cos(a10);
  a41=(a41*a70);
  a41=(a2*a41);
  a43=(a43*a41);
  a55=(a55+a43);
  a55=(a54*a55);
  a56=(a56+a55);
  a56=(a1*a56);
  a20=(a20+a56);
  a7=(a7*a20);
  a47=(a47+a7);
  a37=(a37-a47);
  a44=(a44*a37);
  a45=(a45-a44);
  a45=(a72*a45);
  a44=cos(a3);
  a44=(a44*a25);
  a44=(a59*a44);
  a44=(a2*a44);
  a85=(a85*a44);
  a44=sin(a5);
  a44=(a44*a75);
  a90=(a90*a44);
  a85=(a85-a90);
  a85=(a1*a85);
  a90=sin(a3);
  a90=(a90*a25);
  a90=(a59*a90);
  a90=(a9*a90);
  a90=(a8*a90);
  a85=(a85-a90);
  a90=cos(a10);
  a90=(a90*a70);
  a91=(a91*a90);
  a90=sin(a3);
  a90=(a90*a25);
  a90=(a59*a90);
  a90=(a13*a90);
  a88=(a88*a90);
  a91=(a91-a88);
  a91=(a1*a91);
  a85=(a85-a91);
  a93=(a93*a30);
  a92=(a92*a15);
  a3=sin(a3);
  a3=(a3*a25);
  a3=(a59*a3);
  a16=(a16*a3);
  a92=(a92+a16);
  a31=(a31*a92);
  a93=(a93-a31);
  a93=(a1*a93);
  a85=(a85-a93);
  a87=(a87*a85);
  a45=(a45+a87);
  a45=(a71*a45);
  a4=(a4/a46);
  a87=(a57/a46);
  a87=(a87*a37);
  a4=(a4-a87);
  a4=(a65*a4);
  a87=cos(a34);
  a87=(a87*a73);
  a87=(a59*a87);
  a2=(a2*a87);
  a58=(a58*a2);
  a5=sin(a5);
  a5=(a5*a75);
  a66=(a66*a5);
  a58=(a58-a66);
  a58=(a1*a58);
  a66=sin(a34);
  a66=(a66*a73);
  a66=(a59*a66);
  a9=(a9*a66);
  a8=(a8*a9);
  a58=(a58-a8);
  a10=cos(a10);
  a10=(a10*a70);
  a67=(a67*a10);
  a10=sin(a34);
  a10=(a10*a73);
  a10=(a59*a10);
  a13=(a13*a10);
  a63=(a63*a13);
  a67=(a67-a63);
  a67=(a1*a67);
  a58=(a58+a67);
  a69=(a69*a53);
  a68=(a68*a39);
  a34=sin(a34);
  a34=(a34*a73);
  a59=(a59*a34);
  a42=(a42*a59);
  a68=(a68+a42);
  a54=(a54*a68);
  a69=(a69-a54);
  a1=(a1*a69);
  a58=(a58-a1);
  a57=(a57*a58);
  a4=(a4+a57);
  a4=(a61*a4);
  a45=(a45-a4);
  a45=(-a45);
  if (res[1]!=0) res[1][0]=a45;
  a40=(a40/a46);
  a45=(a84/a46);
  a45=(a45*a37);
  a40=(a40-a45);
  a65=(a65*a40);
  a84=(a84*a58);
  a65=(a65+a84);
  a61=(a61*a65);
  a20=(a20/a46);
  a46=(a64/a46);
  a46=(a46*a37);
  a20=(a20-a46);
  a72=(a72*a20);
  a64=(a64*a85);
  a72=(a72+a64);
  a71=(a71*a72);
  a61=(a61-a71);
  a61=(-a61);
  if (res[1]!=0) res[1][1]=a61;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int thd_bias(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int thd_bias_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int thd_bias_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void thd_bias_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int thd_bias_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void thd_bias_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void thd_bias_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void thd_bias_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int thd_bias_n_in(void) { return 4;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int thd_bias_n_out(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real thd_bias_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* thd_bias_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* thd_bias_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* thd_bias_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* thd_bias_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int thd_bias_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


