/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class humanoid_parameters_lcmt implements lcm.lcm.LCMEncodable
{
    public long control_mode;
    public boolean cheater_mode;
    public boolean display_heightmap;
    public float key_up;
    public float key_down;
    public float key_left;
    public float key_right;
    public float turn_right;
    public float stick_right_vertical;
    public float stick_right_horizontal;
    public float stick_left_vertical;
    public float stick_left_horizontal;
    public boolean jump_trigger;
    public boolean xbox_ctrl;
 
    public humanoid_parameters_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x764dd05493543db5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.humanoid_parameters_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.humanoid_parameters_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.control_mode); 
 
        outs.writeByte( this.cheater_mode ? 1 : 0); 
 
        outs.writeByte( this.display_heightmap ? 1 : 0); 
 
        outs.writeFloat(this.key_up); 
 
        outs.writeFloat(this.key_down); 
 
        outs.writeFloat(this.key_left); 
 
        outs.writeFloat(this.key_right); 
 
        outs.writeFloat(this.turn_right); 
 
        outs.writeFloat(this.stick_right_vertical); 
 
        outs.writeFloat(this.stick_right_horizontal); 
 
        outs.writeFloat(this.stick_left_vertical); 
 
        outs.writeFloat(this.stick_left_horizontal); 
 
        outs.writeByte( this.jump_trigger ? 1 : 0); 
 
        outs.writeByte( this.xbox_ctrl ? 1 : 0); 
 
    }
 
    public humanoid_parameters_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public humanoid_parameters_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.humanoid_parameters_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.humanoid_parameters_lcmt o = new lcmtypes.humanoid_parameters_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.control_mode = ins.readLong();
 
        this.cheater_mode = ins.readByte()!=0;
 
        this.display_heightmap = ins.readByte()!=0;
 
        this.key_up = ins.readFloat();
 
        this.key_down = ins.readFloat();
 
        this.key_left = ins.readFloat();
 
        this.key_right = ins.readFloat();
 
        this.turn_right = ins.readFloat();
 
        this.stick_right_vertical = ins.readFloat();
 
        this.stick_right_horizontal = ins.readFloat();
 
        this.stick_left_vertical = ins.readFloat();
 
        this.stick_left_horizontal = ins.readFloat();
 
        this.jump_trigger = ins.readByte()!=0;
 
        this.xbox_ctrl = ins.readByte()!=0;
 
    }
 
    public lcmtypes.humanoid_parameters_lcmt copy()
    {
        lcmtypes.humanoid_parameters_lcmt outobj = new lcmtypes.humanoid_parameters_lcmt();
        outobj.control_mode = this.control_mode;
 
        outobj.cheater_mode = this.cheater_mode;
 
        outobj.display_heightmap = this.display_heightmap;
 
        outobj.key_up = this.key_up;
 
        outobj.key_down = this.key_down;
 
        outobj.key_left = this.key_left;
 
        outobj.key_right = this.key_right;
 
        outobj.turn_right = this.turn_right;
 
        outobj.stick_right_vertical = this.stick_right_vertical;
 
        outobj.stick_right_horizontal = this.stick_right_horizontal;
 
        outobj.stick_left_vertical = this.stick_left_vertical;
 
        outobj.stick_left_horizontal = this.stick_left_horizontal;
 
        outobj.jump_trigger = this.jump_trigger;
 
        outobj.xbox_ctrl = this.xbox_ctrl;
 
        return outobj;
    }
 
}

