/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class mcvision_state_info_lcmt implements lcm.lcm.LCMEncodable
{
    public float body_pos[];
    public float body_ori_quat_visual[];
    public float body_ori_quat_est[];
    public float jpos[];
 
    public mcvision_state_info_lcmt()
    {
        body_pos = new float[3];
        body_ori_quat_visual = new float[4];
        body_ori_quat_est = new float[4];
        jpos = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1b2eb82c13b66874L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.mcvision_state_info_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.mcvision_state_info_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_pos[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.body_ori_quat_visual[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.body_ori_quat_est[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.jpos[a]); 
        }
 
    }
 
    public mcvision_state_info_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public mcvision_state_info_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.mcvision_state_info_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.mcvision_state_info_lcmt o = new lcmtypes.mcvision_state_info_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.body_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_pos[a] = ins.readFloat();
        }
 
        this.body_ori_quat_visual = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.body_ori_quat_visual[a] = ins.readFloat();
        }
 
        this.body_ori_quat_est = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.body_ori_quat_est[a] = ins.readFloat();
        }
 
        this.jpos = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.jpos[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.mcvision_state_info_lcmt copy()
    {
        lcmtypes.mcvision_state_info_lcmt outobj = new lcmtypes.mcvision_state_info_lcmt();
        outobj.body_pos = new float[(int) 3];
        System.arraycopy(this.body_pos, 0, outobj.body_pos, 0, 3); 
        outobj.body_ori_quat_visual = new float[(int) 4];
        System.arraycopy(this.body_ori_quat_visual, 0, outobj.body_ori_quat_visual, 0, 4); 
        outobj.body_ori_quat_est = new float[(int) 4];
        System.arraycopy(this.body_ori_quat_est, 0, outobj.body_ori_quat_est, 0, 4); 
        outobj.jpos = new float[(int) 12];
        System.arraycopy(this.jpos, 0, outobj.jpos, 0, 12); 
        return outobj;
    }
 
}

