/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class simulator_control_lcmt implements lcm.lcm.LCMEncodable
{
    public boolean key_sim_speed_up;
    public boolean key_sim_speed_down;
    public boolean key_pause;
 
    public simulator_control_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x07c1e3ce3b908892L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.simulator_control_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.simulator_control_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.key_sim_speed_up ? 1 : 0); 
 
        outs.writeByte( this.key_sim_speed_down ? 1 : 0); 
 
        outs.writeByte( this.key_pause ? 1 : 0); 
 
    }
 
    public simulator_control_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public simulator_control_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.simulator_control_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.simulator_control_lcmt o = new lcmtypes.simulator_control_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.key_sim_speed_up = ins.readByte()!=0;
 
        this.key_sim_speed_down = ins.readByte()!=0;
 
        this.key_pause = ins.readByte()!=0;
 
    }
 
    public lcmtypes.simulator_control_lcmt copy()
    {
        lcmtypes.simulator_control_lcmt outobj = new lcmtypes.simulator_control_lcmt();
        outobj.key_sim_speed_up = this.key_sim_speed_up;
 
        outobj.key_sim_speed_down = this.key_sim_speed_down;
 
        outobj.key_pause = this.key_pause;
 
        return outobj;
    }
 
}

