<?xml version="1.0"?>

<robot name="variable_revolute_rotor_branch" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="branch_count" default="4"/>
    <xacro:arg name="depth_count" default="3"/>
    <xacro:property name="branch_count" value="$(arg branch_count)"/>
    <xacro:property name="depth_count" value="$(arg depth_count)"/>
    <xacro:property name="i" value="0"/>
    <xacro:include filename="revolute_rotor_properties.xacro"/>

    <xacro:macro name="build_series_chain_at_each_branch" params="branch_count depth_count i">
        <xacro:if value="${branch_count - i}">
            <xacro:if value="${depth_count - 1}">
                <xacro:nonsequential_serial_chain parent_link_idx="${branch_count - i}"
                    first_child_link_idx="${branch_count + (branch_count - 1) * (depth_count - 1) + 1
                                        - i * (depth_count - 1)}"
                    count="${depth_count}"/>

                <xacro:build_series_chain_at_each_branch branch_count="${branch_count}"
                                                        depth_count="${depth_count}"
                                                        i="${i + 1}"/>
            </xacro:if>
        </xacro:if>
    </xacro:macro>

    <link name="ground"/>
    <link name="Floating Base">
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0. 0. 0."/>
            <inertia ixx="0.1" ixy="0."  ixz="0."
                     iyy="0.1" iyz="0." izz="0.1"/>
        </inertial>
    </link>
    <joint name="world_to_base" type="floating">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="ground"/>
        <child link="Floating Base"/>
    </joint>
    
    <xacro:root_branch branch_count="${branch_count}"/>
    <xacro:build_series_chain_at_each_branch branch_count="${branch_count}"
                                             depth_count="${depth_count}"
                                             i="${i}"/>

</robot>
