/* This file was automatically generated by CasADi 3.6.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int thd_IK_pos(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int thd_IK_pos_alloc_mem(void);
extern "C" int thd_IK_pos_init_mem(int mem);
extern "C" void thd_IK_pos_free_mem(int mem);
extern "C" int thd_IK_pos_checkout(void);
extern "C" void thd_IK_pos_release(int mem);
extern "C" void thd_IK_pos_incref(void);
extern "C" void thd_IK_pos_decref(void);
extern "C" casadi_int thd_IK_pos_n_in(void);
extern "C" casadi_int thd_IK_pos_n_out(void);
extern "C" casadi_real thd_IK_pos_default_in(casadi_int i);
extern "C" const char* thd_IK_pos_name_in(casadi_int i);
extern "C" const char* thd_IK_pos_name_out(casadi_int i);
extern "C" const casadi_int* thd_IK_pos_sparsity_in(casadi_int i);
extern "C" const casadi_int* thd_IK_pos_sparsity_out(casadi_int i);
extern "C" int thd_IK_pos_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define thd_IK_pos_SZ_ARG 1
#define thd_IK_pos_SZ_RES 1
#define thd_IK_pos_SZ_IW 0
#define thd_IK_pos_SZ_W 20
