/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class actuator_lcmt : LCM.LCM.LCMEncodable
    {
        public int iter;
        public float[] qdot;
        public float[] tau;
 
        public actuator_lcmt()
        {
            qdot = new float[10];
            tau = new float[10];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x645f6201325e366dL;
 
        static actuator_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.actuator_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.actuator_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.iter); 
 
            for (int a = 0; a < 10; a++) {
                outs.Write(this.qdot[a]); 
            }
 
            for (int a = 0; a < 10; a++) {
                outs.Write(this.tau[a]); 
            }
 
        }
 
        public actuator_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public actuator_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.actuator_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.actuator_lcmt o = new LCMTypes.actuator_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.iter = ins.ReadInt32();
 
            this.qdot = new float[(int) 10];
            for (int a = 0; a < 10; a++) {
                this.qdot[a] = ins.ReadSingle();
            }
 
            this.tau = new float[(int) 10];
            for (int a = 0; a < 10; a++) {
                this.tau[a] = ins.ReadSingle();
            }
 
        }
 
        public LCMTypes.actuator_lcmt Copy()
        {
            LCMTypes.actuator_lcmt outobj = new LCMTypes.actuator_lcmt();
            outobj.iter = this.iter;
 
            outobj.qdot = new float[(int) 10];
            for (int a = 0; a < 10; a++) {
                outobj.qdot[a] = this.qdot[a];
            }
 
            outobj.tau = new float[(int) 10];
            for (int a = 0; a < 10; a++) {
                outobj.tau[a] = this.tau[a];
            }
 
            return outobj;
        }
    }
}

