/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class humanoid_data_lcmt : LCM.LCM.LCMEncodable
    {
        public float[] q_hipz;
        public float[] q_hipx;
        public float[] q_hipy;
        public float[] q_knee;
        public float[] q_ankle;
        public float[] q_shouldery;
        public float[] q_shoulderx;
        public float[] q_shoulderz;
        public float[] q_elbow;
        public float[] qd_hipz;
        public float[] qd_hipx;
        public float[] qd_hipy;
        public float[] qd_knee;
        public float[] qd_ankle;
        public float[] qd_shouldery;
        public float[] qd_shoulderx;
        public float[] qd_shoulderz;
        public float[] qd_elbow;
        public float[] tau_hipz;
        public float[] tau_hipx;
        public float[] tau_hipy;
        public float[] tau_knee;
        public float[] tau_ankle;
        public float[] tau_shouldery;
        public float[] tau_shoulderx;
        public float[] tau_shoulderz;
        public float[] tau_elbow;
        public int[] flags;
        public int spi_driver_status;
 
        public humanoid_data_lcmt()
        {
            q_hipz = new float[2];
            q_hipx = new float[2];
            q_hipy = new float[2];
            q_knee = new float[2];
            q_ankle = new float[2];
            q_shouldery = new float[2];
            q_shoulderx = new float[2];
            q_shoulderz = new float[2];
            q_elbow = new float[2];
            qd_hipz = new float[2];
            qd_hipx = new float[2];
            qd_hipy = new float[2];
            qd_knee = new float[2];
            qd_ankle = new float[2];
            qd_shouldery = new float[2];
            qd_shoulderx = new float[2];
            qd_shoulderz = new float[2];
            qd_elbow = new float[2];
            tau_hipz = new float[2];
            tau_hipx = new float[2];
            tau_hipy = new float[2];
            tau_knee = new float[2];
            tau_ankle = new float[2];
            tau_shouldery = new float[2];
            tau_shoulderx = new float[2];
            tau_shoulderz = new float[2];
            tau_elbow = new float[2];
            flags = new int[6];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0092fdd14e5ce4ceL;
 
        static humanoid_data_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.humanoid_data_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.humanoid_data_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_hipz[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_hipx[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_hipy[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_knee[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_ankle[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_shouldery[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_shoulderx[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_shoulderz[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q_elbow[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_hipz[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_hipx[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_hipy[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_knee[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_ankle[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_shouldery[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_shoulderx[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_shoulderz[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.qd_elbow[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_hipz[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_hipx[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_hipy[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_knee[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_ankle[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_shouldery[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_shoulderx[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_shoulderz[a]); 
            }
 
            for (int a = 0; a < 2; a++) {
                outs.Write(this.tau_elbow[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.flags[a]); 
            }
 
            outs.Write(this.spi_driver_status); 
 
        }
 
        public humanoid_data_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public humanoid_data_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.humanoid_data_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.humanoid_data_lcmt o = new LCMTypes.humanoid_data_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.q_hipz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_hipz[a] = ins.ReadSingle();
            }
 
            this.q_hipx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_hipx[a] = ins.ReadSingle();
            }
 
            this.q_hipy = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_hipy[a] = ins.ReadSingle();
            }
 
            this.q_knee = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_knee[a] = ins.ReadSingle();
            }
 
            this.q_ankle = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_ankle[a] = ins.ReadSingle();
            }
 
            this.q_shouldery = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_shouldery[a] = ins.ReadSingle();
            }
 
            this.q_shoulderx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_shoulderx[a] = ins.ReadSingle();
            }
 
            this.q_shoulderz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_shoulderz[a] = ins.ReadSingle();
            }
 
            this.q_elbow = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q_elbow[a] = ins.ReadSingle();
            }
 
            this.qd_hipz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_hipz[a] = ins.ReadSingle();
            }
 
            this.qd_hipx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_hipx[a] = ins.ReadSingle();
            }
 
            this.qd_hipy = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_hipy[a] = ins.ReadSingle();
            }
 
            this.qd_knee = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_knee[a] = ins.ReadSingle();
            }
 
            this.qd_ankle = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_ankle[a] = ins.ReadSingle();
            }
 
            this.qd_shouldery = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_shouldery[a] = ins.ReadSingle();
            }
 
            this.qd_shoulderx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_shoulderx[a] = ins.ReadSingle();
            }
 
            this.qd_shoulderz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_shoulderz[a] = ins.ReadSingle();
            }
 
            this.qd_elbow = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.qd_elbow[a] = ins.ReadSingle();
            }
 
            this.tau_hipz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_hipz[a] = ins.ReadSingle();
            }
 
            this.tau_hipx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_hipx[a] = ins.ReadSingle();
            }
 
            this.tau_hipy = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_hipy[a] = ins.ReadSingle();
            }
 
            this.tau_knee = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_knee[a] = ins.ReadSingle();
            }
 
            this.tau_ankle = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_ankle[a] = ins.ReadSingle();
            }
 
            this.tau_shouldery = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_shouldery[a] = ins.ReadSingle();
            }
 
            this.tau_shoulderx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_shoulderx[a] = ins.ReadSingle();
            }
 
            this.tau_shoulderz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_shoulderz[a] = ins.ReadSingle();
            }
 
            this.tau_elbow = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.tau_elbow[a] = ins.ReadSingle();
            }
 
            this.flags = new int[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.flags[a] = ins.ReadInt32();
            }
 
            this.spi_driver_status = ins.ReadInt32();
 
        }
 
        public LCMTypes.humanoid_data_lcmt Copy()
        {
            LCMTypes.humanoid_data_lcmt outobj = new LCMTypes.humanoid_data_lcmt();
            outobj.q_hipz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_hipz[a] = this.q_hipz[a];
            }
 
            outobj.q_hipx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_hipx[a] = this.q_hipx[a];
            }
 
            outobj.q_hipy = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_hipy[a] = this.q_hipy[a];
            }
 
            outobj.q_knee = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_knee[a] = this.q_knee[a];
            }
 
            outobj.q_ankle = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_ankle[a] = this.q_ankle[a];
            }
 
            outobj.q_shouldery = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_shouldery[a] = this.q_shouldery[a];
            }
 
            outobj.q_shoulderx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_shoulderx[a] = this.q_shoulderx[a];
            }
 
            outobj.q_shoulderz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_shoulderz[a] = this.q_shoulderz[a];
            }
 
            outobj.q_elbow = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q_elbow[a] = this.q_elbow[a];
            }
 
            outobj.qd_hipz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_hipz[a] = this.qd_hipz[a];
            }
 
            outobj.qd_hipx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_hipx[a] = this.qd_hipx[a];
            }
 
            outobj.qd_hipy = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_hipy[a] = this.qd_hipy[a];
            }
 
            outobj.qd_knee = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_knee[a] = this.qd_knee[a];
            }
 
            outobj.qd_ankle = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_ankle[a] = this.qd_ankle[a];
            }
 
            outobj.qd_shouldery = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_shouldery[a] = this.qd_shouldery[a];
            }
 
            outobj.qd_shoulderx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_shoulderx[a] = this.qd_shoulderx[a];
            }
 
            outobj.qd_shoulderz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_shoulderz[a] = this.qd_shoulderz[a];
            }
 
            outobj.qd_elbow = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.qd_elbow[a] = this.qd_elbow[a];
            }
 
            outobj.tau_hipz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_hipz[a] = this.tau_hipz[a];
            }
 
            outobj.tau_hipx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_hipx[a] = this.tau_hipx[a];
            }
 
            outobj.tau_hipy = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_hipy[a] = this.tau_hipy[a];
            }
 
            outobj.tau_knee = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_knee[a] = this.tau_knee[a];
            }
 
            outobj.tau_ankle = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_ankle[a] = this.tau_ankle[a];
            }
 
            outobj.tau_shouldery = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_shouldery[a] = this.tau_shouldery[a];
            }
 
            outobj.tau_shoulderx = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_shoulderx[a] = this.tau_shoulderx[a];
            }
 
            outobj.tau_shoulderz = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_shoulderz[a] = this.tau_shoulderz[a];
            }
 
            outobj.tau_elbow = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.tau_elbow[a] = this.tau_elbow[a];
            }
 
            outobj.flags = new int[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.flags[a] = this.flags[a];
            }
 
            outobj.spi_driver_status = this.spi_driver_status;
 
            return outobj;
        }
    }
}

