/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class humanoid_arm_recovery_outputs_lcmt : LCM.LCM.LCMEncodable
    {
        public int optim_iter;
        public int opt_solved;
        public double cpu_opt_time_microseconds;
        public double t_sent;
        public double time_start;
        public double[] p_body;
        public double[] rpy;
        public double[] v_body;
        public double[] omega_body;
        public double[] c_toe;
        public double[] c_heel;
        public double[] f_toe;
        public double[] f_heel;
        public double[] r;
        public double[] rdot;
        public double[] rddot;
        public double[] h;
        public double[] hdot;
        public double[] vG;
        public double[] vGdot;
        public double[] jpos;
        public double[] jvel;
        public double[] a_body;
        public double[] alf_body;
        public double[] jacc;
        public double[] fb_dist;
        public double iter_dist;
        public double[] vLimb;
        public double[] contact_state;
 
        public humanoid_arm_recovery_outputs_lcmt()
        {
            p_body = new double[3];
            rpy = new double[3];
            v_body = new double[3];
            omega_body = new double[3];
            c_toe = new double[6];
            c_heel = new double[6];
            f_toe = new double[6];
            f_heel = new double[6];
            r = new double[3];
            rdot = new double[3];
            rddot = new double[3];
            h = new double[6];
            hdot = new double[6];
            vG = new double[6];
            vGdot = new double[6];
            jpos = new double[18];
            jvel = new double[18];
            a_body = new double[3];
            alf_body = new double[3];
            jacc = new double[18];
            fb_dist = new double[6];
            vLimb = new double[12];
            contact_state = new double[6];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xbb37a25edeaa3345L;
 
        static humanoid_arm_recovery_outputs_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.humanoid_arm_recovery_outputs_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.humanoid_arm_recovery_outputs_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.optim_iter); 
 
            outs.Write(this.opt_solved); 
 
            outs.Write(this.cpu_opt_time_microseconds); 
 
            outs.Write(this.t_sent); 
 
            outs.Write(this.time_start); 
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.p_body[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.rpy[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.v_body[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.omega_body[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.c_toe[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.c_heel[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.f_toe[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.f_heel[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.r[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.rdot[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.rddot[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.h[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.hdot[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.vG[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.vGdot[a]); 
            }
 
            for (int a = 0; a < 18; a++) {
                outs.Write(this.jpos[a]); 
            }
 
            for (int a = 0; a < 18; a++) {
                outs.Write(this.jvel[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.a_body[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.alf_body[a]); 
            }
 
            for (int a = 0; a < 18; a++) {
                outs.Write(this.jacc[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.fb_dist[a]); 
            }
 
            outs.Write(this.iter_dist); 
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.vLimb[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.contact_state[a]); 
            }
 
        }
 
        public humanoid_arm_recovery_outputs_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public humanoid_arm_recovery_outputs_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.humanoid_arm_recovery_outputs_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.humanoid_arm_recovery_outputs_lcmt o = new LCMTypes.humanoid_arm_recovery_outputs_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.optim_iter = ins.ReadInt32();
 
            this.opt_solved = ins.ReadInt32();
 
            this.cpu_opt_time_microseconds = ins.ReadDouble();
 
            this.t_sent = ins.ReadDouble();
 
            this.time_start = ins.ReadDouble();
 
            this.p_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.p_body[a] = ins.ReadDouble();
            }
 
            this.rpy = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.rpy[a] = ins.ReadDouble();
            }
 
            this.v_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.v_body[a] = ins.ReadDouble();
            }
 
            this.omega_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.omega_body[a] = ins.ReadDouble();
            }
 
            this.c_toe = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.c_toe[a] = ins.ReadDouble();
            }
 
            this.c_heel = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.c_heel[a] = ins.ReadDouble();
            }
 
            this.f_toe = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.f_toe[a] = ins.ReadDouble();
            }
 
            this.f_heel = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.f_heel[a] = ins.ReadDouble();
            }
 
            this.r = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.r[a] = ins.ReadDouble();
            }
 
            this.rdot = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.rdot[a] = ins.ReadDouble();
            }
 
            this.rddot = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.rddot[a] = ins.ReadDouble();
            }
 
            this.h = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.h[a] = ins.ReadDouble();
            }
 
            this.hdot = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.hdot[a] = ins.ReadDouble();
            }
 
            this.vG = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.vG[a] = ins.ReadDouble();
            }
 
            this.vGdot = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.vGdot[a] = ins.ReadDouble();
            }
 
            this.jpos = new double[(int) 18];
            for (int a = 0; a < 18; a++) {
                this.jpos[a] = ins.ReadDouble();
            }
 
            this.jvel = new double[(int) 18];
            for (int a = 0; a < 18; a++) {
                this.jvel[a] = ins.ReadDouble();
            }
 
            this.a_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.a_body[a] = ins.ReadDouble();
            }
 
            this.alf_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.alf_body[a] = ins.ReadDouble();
            }
 
            this.jacc = new double[(int) 18];
            for (int a = 0; a < 18; a++) {
                this.jacc[a] = ins.ReadDouble();
            }
 
            this.fb_dist = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.fb_dist[a] = ins.ReadDouble();
            }
 
            this.iter_dist = ins.ReadDouble();
 
            this.vLimb = new double[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.vLimb[a] = ins.ReadDouble();
            }
 
            this.contact_state = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.contact_state[a] = ins.ReadDouble();
            }
 
        }
 
        public LCMTypes.humanoid_arm_recovery_outputs_lcmt Copy()
        {
            LCMTypes.humanoid_arm_recovery_outputs_lcmt outobj = new LCMTypes.humanoid_arm_recovery_outputs_lcmt();
            outobj.optim_iter = this.optim_iter;
 
            outobj.opt_solved = this.opt_solved;
 
            outobj.cpu_opt_time_microseconds = this.cpu_opt_time_microseconds;
 
            outobj.t_sent = this.t_sent;
 
            outobj.time_start = this.time_start;
 
            outobj.p_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.p_body[a] = this.p_body[a];
            }
 
            outobj.rpy = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.rpy[a] = this.rpy[a];
            }
 
            outobj.v_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.v_body[a] = this.v_body[a];
            }
 
            outobj.omega_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.omega_body[a] = this.omega_body[a];
            }
 
            outobj.c_toe = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.c_toe[a] = this.c_toe[a];
            }
 
            outobj.c_heel = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.c_heel[a] = this.c_heel[a];
            }
 
            outobj.f_toe = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.f_toe[a] = this.f_toe[a];
            }
 
            outobj.f_heel = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.f_heel[a] = this.f_heel[a];
            }
 
            outobj.r = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.r[a] = this.r[a];
            }
 
            outobj.rdot = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.rdot[a] = this.rdot[a];
            }
 
            outobj.rddot = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.rddot[a] = this.rddot[a];
            }
 
            outobj.h = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.h[a] = this.h[a];
            }
 
            outobj.hdot = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.hdot[a] = this.hdot[a];
            }
 
            outobj.vG = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.vG[a] = this.vG[a];
            }
 
            outobj.vGdot = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.vGdot[a] = this.vGdot[a];
            }
 
            outobj.jpos = new double[(int) 18];
            for (int a = 0; a < 18; a++) {
                outobj.jpos[a] = this.jpos[a];
            }
 
            outobj.jvel = new double[(int) 18];
            for (int a = 0; a < 18; a++) {
                outobj.jvel[a] = this.jvel[a];
            }
 
            outobj.a_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.a_body[a] = this.a_body[a];
            }
 
            outobj.alf_body = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.alf_body[a] = this.alf_body[a];
            }
 
            outobj.jacc = new double[(int) 18];
            for (int a = 0; a < 18; a++) {
                outobj.jacc[a] = this.jacc[a];
            }
 
            outobj.fb_dist = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.fb_dist[a] = this.fb_dist[a];
            }
 
            outobj.iter_dist = this.iter_dist;
 
            outobj.vLimb = new double[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.vLimb[a] = this.vLimb[a];
            }
 
            outobj.contact_state = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.contact_state[a] = this.contact_state[a];
            }
 
            return outobj;
        }
    }
}

