/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class leg_control_command_lcmt : LCM.LCM.LCMEncodable
    {
        public float[] tau_ff;
        public float[] f_ff;
        public float[] q_des;
        public float[] qd_des;
        public float[] p_des;
        public float[] v_des;
        public float[] kp_cartesian;
        public float[] kd_cartesian;
        public float[] kp_joint;
        public float[] kd_joint;
 
        public leg_control_command_lcmt()
        {
            tau_ff = new float[12];
            f_ff = new float[12];
            q_des = new float[12];
            qd_des = new float[12];
            p_des = new float[12];
            v_des = new float[12];
            kp_cartesian = new float[12];
            kd_cartesian = new float[12];
            kp_joint = new float[12];
            kd_joint = new float[12];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x93bfbc95a989bb67L;
 
        static leg_control_command_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.leg_control_command_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.leg_control_command_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 12; a++) {
                outs.Write(this.tau_ff[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.f_ff[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.q_des[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.qd_des[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.p_des[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.v_des[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.kp_cartesian[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.kd_cartesian[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.kp_joint[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                outs.Write(this.kd_joint[a]); 
            }
 
        }
 
        public leg_control_command_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public leg_control_command_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.leg_control_command_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.leg_control_command_lcmt o = new LCMTypes.leg_control_command_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.tau_ff = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.tau_ff[a] = ins.ReadSingle();
            }
 
            this.f_ff = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.f_ff[a] = ins.ReadSingle();
            }
 
            this.q_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.q_des[a] = ins.ReadSingle();
            }
 
            this.qd_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.qd_des[a] = ins.ReadSingle();
            }
 
            this.p_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.p_des[a] = ins.ReadSingle();
            }
 
            this.v_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.v_des[a] = ins.ReadSingle();
            }
 
            this.kp_cartesian = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.kp_cartesian[a] = ins.ReadSingle();
            }
 
            this.kd_cartesian = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.kd_cartesian[a] = ins.ReadSingle();
            }
 
            this.kp_joint = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.kp_joint[a] = ins.ReadSingle();
            }
 
            this.kd_joint = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                this.kd_joint[a] = ins.ReadSingle();
            }
 
        }
 
        public LCMTypes.leg_control_command_lcmt Copy()
        {
            LCMTypes.leg_control_command_lcmt outobj = new LCMTypes.leg_control_command_lcmt();
            outobj.tau_ff = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.tau_ff[a] = this.tau_ff[a];
            }
 
            outobj.f_ff = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.f_ff[a] = this.f_ff[a];
            }
 
            outobj.q_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.q_des[a] = this.q_des[a];
            }
 
            outobj.qd_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.qd_des[a] = this.qd_des[a];
            }
 
            outobj.p_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.p_des[a] = this.p_des[a];
            }
 
            outobj.v_des = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.v_des[a] = this.v_des[a];
            }
 
            outobj.kp_cartesian = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.kp_cartesian[a] = this.kp_cartesian[a];
            }
 
            outobj.kd_cartesian = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.kd_cartesian[a] = this.kd_cartesian[a];
            }
 
            outobj.kp_joint = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.kp_joint[a] = this.kp_joint[a];
            }
 
            outobj.kd_joint = new float[(int) 12];
            for (int a = 0; a < 12; a++) {
                outobj.kd_joint[a] = this.kd_joint[a];
            }
 
            return outobj;
        }
    }
}

