/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class openchain2dof_lcmt : LCM.LCM.LCMEncodable
    {
        public float[] q;
 
        public openchain2dof_lcmt()
        {
            q = new float[2];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x90d80e6403e20bffL;
 
        static openchain2dof_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.openchain2dof_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.openchain2dof_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 2; a++) {
                outs.Write(this.q[a]); 
            }
 
        }
 
        public openchain2dof_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public openchain2dof_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.openchain2dof_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.openchain2dof_lcmt o = new LCMTypes.openchain2dof_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.q = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.q[a] = ins.ReadSingle();
            }
 
        }
 
        public LCMTypes.openchain2dof_lcmt Copy()
        {
            LCMTypes.openchain2dof_lcmt outobj = new LCMTypes.openchain2dof_lcmt();
            outobj.q = new float[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.q[a] = this.q[a];
            }
 
            return outobj;
        }
    }
}

