/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class path_lcmt : LCM.LCM.LCMEncodable
    {
        public int pathLength;
        public double[] path;
 
        public path_lcmt()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x706f33a7f85c184aL;
 
        static path_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.path_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.path_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.pathLength); 
 
            for (int a = 0; a < this.pathLength; a++) {
                outs.Write(this.path[a]); 
            }
 
        }
 
        public path_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public path_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.path_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.path_lcmt o = new LCMTypes.path_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.pathLength = ins.ReadInt32();
 
            this.path = new double[(int) pathLength];
            for (int a = 0; a < this.pathLength; a++) {
                this.path[a] = ins.ReadDouble();
            }
 
        }
 
        public LCMTypes.path_lcmt Copy()
        {
            LCMTypes.path_lcmt outobj = new LCMTypes.path_lcmt();
            outobj.pathLength = this.pathLength;
 
            outobj.path = new double[(int) pathLength];
            for (int a = 0; a < this.pathLength; a++) {
                outobj.path[a] = this.path[a];
            }
 
            return outobj;
        }
    }
}

