/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class qkdmpc_inputs_lcmt : LCM.LCM.LCMEncodable
    {
        public int NUM_X_VAR;
        public int NUM_U_VAR;
        public int NUM_TIMESTEPS;
        public int NUM_U_TIMESTEPS;
        public int NUM_X_VAR_TRAJ;
        public int NUM_U_VAR_TRAJ;
        public int NUM_OPT_VAR_TRAJ;
        public int NUM_G_CONSTRAINTS;
        public int NUM_X_CONSTRAINTS;
        public int NUM_LEGS;
        public int NUM_LEGS_x3;
        public int NUM_FB_DOF;
        public int NUM_GAIT_TABLE;
        public int NUM_GAIT_PHASE;
        public int DETECT_SIMPLE_BOUNDS;
        public double[] Xref;
        public double[] Uref;
        public double[] gait_schedule;
        public double[] dt;
        public double[] t_opt;
        public double[] q_min;
        public double[] q_max;
        public double[] qd_min;
        public double[] qd_max;
        public double[] rd_init;
        public double[] q_init;
        public double[] qd_init;
        public double[] c_init;
        public double[] q_term_min;
        public double[] q_term_max;
        public double[] qd_term_min;
        public double[] qd_term_max;
        public double[] r_term_min;
        public double[] r_term_max;
        public double[] rd_term_min;
        public double[] rd_term_max;
        public double[] h_term_min;
        public double[] h_term_max;
        public double[] Qq;
        public double[] Qv;
        public double[] Qr;
        public double[] Qh;
        public double[] Qc;
        public double[] QNq;
        public double[] QNv;
        public double[] QNr;
        public double[] QNh;
        public double[] QNc;
        public double[] X_init_guess;
        public double[] lambdaG_init_guess;
        public double[] lambdaX_init_guess;
        public double[] Phi;
 
        public qkdmpc_inputs_lcmt()
        {
            rd_init = new double[3];
            q_init = new double[6];
            qd_init = new double[3];
            r_term_min = new double[3];
            r_term_max = new double[3];
            rd_term_min = new double[3];
            rd_term_max = new double[3];
            h_term_min = new double[3];
            h_term_max = new double[3];
            Qr = new double[6];
            Qh = new double[3];
            QNr = new double[6];
            QNh = new double[3];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x2bba20560214db4fL;
 
        static qkdmpc_inputs_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.qkdmpc_inputs_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.qkdmpc_inputs_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.NUM_X_VAR); 
 
            outs.Write(this.NUM_U_VAR); 
 
            outs.Write(this.NUM_TIMESTEPS); 
 
            outs.Write(this.NUM_U_TIMESTEPS); 
 
            outs.Write(this.NUM_X_VAR_TRAJ); 
 
            outs.Write(this.NUM_U_VAR_TRAJ); 
 
            outs.Write(this.NUM_OPT_VAR_TRAJ); 
 
            outs.Write(this.NUM_G_CONSTRAINTS); 
 
            outs.Write(this.NUM_X_CONSTRAINTS); 
 
            outs.Write(this.NUM_LEGS); 
 
            outs.Write(this.NUM_LEGS_x3); 
 
            outs.Write(this.NUM_FB_DOF); 
 
            outs.Write(this.NUM_GAIT_TABLE); 
 
            outs.Write(this.NUM_GAIT_PHASE); 
 
            outs.Write(this.DETECT_SIMPLE_BOUNDS); 
 
            for (int a = 0; a < this.NUM_X_VAR_TRAJ; a++) {
                outs.Write(this.Xref[a]); 
            }
 
            for (int a = 0; a < this.NUM_U_VAR_TRAJ; a++) {
                outs.Write(this.Uref[a]); 
            }
 
            for (int a = 0; a < this.NUM_GAIT_TABLE; a++) {
                outs.Write(this.gait_schedule[a]); 
            }
 
            for (int a = 0; a < this.NUM_U_TIMESTEPS; a++) {
                outs.Write(this.dt[a]); 
            }
 
            for (int a = 0; a < this.NUM_TIMESTEPS; a++) {
                outs.Write(this.t_opt[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.q_min[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.q_max[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.qd_min[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.qd_max[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.rd_init[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.q_init[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.qd_init[a]); 
            }
 
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                outs.Write(this.c_init[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.q_term_min[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.q_term_max[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.qd_term_min[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.qd_term_max[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.r_term_min[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.r_term_max[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.rd_term_min[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.rd_term_max[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.h_term_min[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.h_term_max[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.Qq[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.Qv[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.Qr[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.Qh[a]); 
            }
 
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                outs.Write(this.Qc[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.QNq[a]); 
            }
 
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outs.Write(this.QNv[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                outs.Write(this.QNr[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.QNh[a]); 
            }
 
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                outs.Write(this.QNc[a]); 
            }
 
            for (int a = 0; a < this.NUM_OPT_VAR_TRAJ; a++) {
                outs.Write(this.X_init_guess[a]); 
            }
 
            for (int a = 0; a < this.NUM_G_CONSTRAINTS; a++) {
                outs.Write(this.lambdaG_init_guess[a]); 
            }
 
            for (int a = 0; a < this.NUM_X_CONSTRAINTS; a++) {
                outs.Write(this.lambdaX_init_guess[a]); 
            }
 
            for (int a = 0; a < this.NUM_GAIT_PHASE; a++) {
                outs.Write(this.Phi[a]); 
            }
 
        }
 
        public qkdmpc_inputs_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public qkdmpc_inputs_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.qkdmpc_inputs_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.qkdmpc_inputs_lcmt o = new LCMTypes.qkdmpc_inputs_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.NUM_X_VAR = ins.ReadInt32();
 
            this.NUM_U_VAR = ins.ReadInt32();
 
            this.NUM_TIMESTEPS = ins.ReadInt32();
 
            this.NUM_U_TIMESTEPS = ins.ReadInt32();
 
            this.NUM_X_VAR_TRAJ = ins.ReadInt32();
 
            this.NUM_U_VAR_TRAJ = ins.ReadInt32();
 
            this.NUM_OPT_VAR_TRAJ = ins.ReadInt32();
 
            this.NUM_G_CONSTRAINTS = ins.ReadInt32();
 
            this.NUM_X_CONSTRAINTS = ins.ReadInt32();
 
            this.NUM_LEGS = ins.ReadInt32();
 
            this.NUM_LEGS_x3 = ins.ReadInt32();
 
            this.NUM_FB_DOF = ins.ReadInt32();
 
            this.NUM_GAIT_TABLE = ins.ReadInt32();
 
            this.NUM_GAIT_PHASE = ins.ReadInt32();
 
            this.DETECT_SIMPLE_BOUNDS = ins.ReadInt32();
 
            this.Xref = new double[(int) NUM_X_VAR_TRAJ];
            for (int a = 0; a < this.NUM_X_VAR_TRAJ; a++) {
                this.Xref[a] = ins.ReadDouble();
            }
 
            this.Uref = new double[(int) NUM_U_VAR_TRAJ];
            for (int a = 0; a < this.NUM_U_VAR_TRAJ; a++) {
                this.Uref[a] = ins.ReadDouble();
            }
 
            this.gait_schedule = new double[(int) NUM_GAIT_TABLE];
            for (int a = 0; a < this.NUM_GAIT_TABLE; a++) {
                this.gait_schedule[a] = ins.ReadDouble();
            }
 
            this.dt = new double[(int) NUM_U_TIMESTEPS];
            for (int a = 0; a < this.NUM_U_TIMESTEPS; a++) {
                this.dt[a] = ins.ReadDouble();
            }
 
            this.t_opt = new double[(int) NUM_TIMESTEPS];
            for (int a = 0; a < this.NUM_TIMESTEPS; a++) {
                this.t_opt[a] = ins.ReadDouble();
            }
 
            this.q_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.q_min[a] = ins.ReadDouble();
            }
 
            this.q_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.q_max[a] = ins.ReadDouble();
            }
 
            this.qd_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.qd_min[a] = ins.ReadDouble();
            }
 
            this.qd_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.qd_max[a] = ins.ReadDouble();
            }
 
            this.rd_init = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.rd_init[a] = ins.ReadDouble();
            }
 
            this.q_init = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.q_init[a] = ins.ReadDouble();
            }
 
            this.qd_init = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.qd_init[a] = ins.ReadDouble();
            }
 
            this.c_init = new double[(int) NUM_LEGS_x3];
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                this.c_init[a] = ins.ReadDouble();
            }
 
            this.q_term_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.q_term_min[a] = ins.ReadDouble();
            }
 
            this.q_term_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.q_term_max[a] = ins.ReadDouble();
            }
 
            this.qd_term_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.qd_term_min[a] = ins.ReadDouble();
            }
 
            this.qd_term_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.qd_term_max[a] = ins.ReadDouble();
            }
 
            this.r_term_min = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.r_term_min[a] = ins.ReadDouble();
            }
 
            this.r_term_max = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.r_term_max[a] = ins.ReadDouble();
            }
 
            this.rd_term_min = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.rd_term_min[a] = ins.ReadDouble();
            }
 
            this.rd_term_max = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.rd_term_max[a] = ins.ReadDouble();
            }
 
            this.h_term_min = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.h_term_min[a] = ins.ReadDouble();
            }
 
            this.h_term_max = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.h_term_max[a] = ins.ReadDouble();
            }
 
            this.Qq = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.Qq[a] = ins.ReadDouble();
            }
 
            this.Qv = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.Qv[a] = ins.ReadDouble();
            }
 
            this.Qr = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.Qr[a] = ins.ReadDouble();
            }
 
            this.Qh = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.Qh[a] = ins.ReadDouble();
            }
 
            this.Qc = new double[(int) NUM_LEGS_x3];
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                this.Qc[a] = ins.ReadDouble();
            }
 
            this.QNq = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.QNq[a] = ins.ReadDouble();
            }
 
            this.QNv = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                this.QNv[a] = ins.ReadDouble();
            }
 
            this.QNr = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                this.QNr[a] = ins.ReadDouble();
            }
 
            this.QNh = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.QNh[a] = ins.ReadDouble();
            }
 
            this.QNc = new double[(int) NUM_LEGS_x3];
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                this.QNc[a] = ins.ReadDouble();
            }
 
            this.X_init_guess = new double[(int) NUM_OPT_VAR_TRAJ];
            for (int a = 0; a < this.NUM_OPT_VAR_TRAJ; a++) {
                this.X_init_guess[a] = ins.ReadDouble();
            }
 
            this.lambdaG_init_guess = new double[(int) NUM_G_CONSTRAINTS];
            for (int a = 0; a < this.NUM_G_CONSTRAINTS; a++) {
                this.lambdaG_init_guess[a] = ins.ReadDouble();
            }
 
            this.lambdaX_init_guess = new double[(int) NUM_X_CONSTRAINTS];
            for (int a = 0; a < this.NUM_X_CONSTRAINTS; a++) {
                this.lambdaX_init_guess[a] = ins.ReadDouble();
            }
 
            this.Phi = new double[(int) NUM_GAIT_PHASE];
            for (int a = 0; a < this.NUM_GAIT_PHASE; a++) {
                this.Phi[a] = ins.ReadDouble();
            }
 
        }
 
        public LCMTypes.qkdmpc_inputs_lcmt Copy()
        {
            LCMTypes.qkdmpc_inputs_lcmt outobj = new LCMTypes.qkdmpc_inputs_lcmt();
            outobj.NUM_X_VAR = this.NUM_X_VAR;
 
            outobj.NUM_U_VAR = this.NUM_U_VAR;
 
            outobj.NUM_TIMESTEPS = this.NUM_TIMESTEPS;
 
            outobj.NUM_U_TIMESTEPS = this.NUM_U_TIMESTEPS;
 
            outobj.NUM_X_VAR_TRAJ = this.NUM_X_VAR_TRAJ;
 
            outobj.NUM_U_VAR_TRAJ = this.NUM_U_VAR_TRAJ;
 
            outobj.NUM_OPT_VAR_TRAJ = this.NUM_OPT_VAR_TRAJ;
 
            outobj.NUM_G_CONSTRAINTS = this.NUM_G_CONSTRAINTS;
 
            outobj.NUM_X_CONSTRAINTS = this.NUM_X_CONSTRAINTS;
 
            outobj.NUM_LEGS = this.NUM_LEGS;
 
            outobj.NUM_LEGS_x3 = this.NUM_LEGS_x3;
 
            outobj.NUM_FB_DOF = this.NUM_FB_DOF;
 
            outobj.NUM_GAIT_TABLE = this.NUM_GAIT_TABLE;
 
            outobj.NUM_GAIT_PHASE = this.NUM_GAIT_PHASE;
 
            outobj.DETECT_SIMPLE_BOUNDS = this.DETECT_SIMPLE_BOUNDS;
 
            outobj.Xref = new double[(int) NUM_X_VAR_TRAJ];
            for (int a = 0; a < this.NUM_X_VAR_TRAJ; a++) {
                outobj.Xref[a] = this.Xref[a];
            }
 
            outobj.Uref = new double[(int) NUM_U_VAR_TRAJ];
            for (int a = 0; a < this.NUM_U_VAR_TRAJ; a++) {
                outobj.Uref[a] = this.Uref[a];
            }
 
            outobj.gait_schedule = new double[(int) NUM_GAIT_TABLE];
            for (int a = 0; a < this.NUM_GAIT_TABLE; a++) {
                outobj.gait_schedule[a] = this.gait_schedule[a];
            }
 
            outobj.dt = new double[(int) NUM_U_TIMESTEPS];
            for (int a = 0; a < this.NUM_U_TIMESTEPS; a++) {
                outobj.dt[a] = this.dt[a];
            }
 
            outobj.t_opt = new double[(int) NUM_TIMESTEPS];
            for (int a = 0; a < this.NUM_TIMESTEPS; a++) {
                outobj.t_opt[a] = this.t_opt[a];
            }
 
            outobj.q_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.q_min[a] = this.q_min[a];
            }
 
            outobj.q_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.q_max[a] = this.q_max[a];
            }
 
            outobj.qd_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.qd_min[a] = this.qd_min[a];
            }
 
            outobj.qd_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.qd_max[a] = this.qd_max[a];
            }
 
            outobj.rd_init = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.rd_init[a] = this.rd_init[a];
            }
 
            outobj.q_init = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.q_init[a] = this.q_init[a];
            }
 
            outobj.qd_init = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.qd_init[a] = this.qd_init[a];
            }
 
            outobj.c_init = new double[(int) NUM_LEGS_x3];
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                outobj.c_init[a] = this.c_init[a];
            }
 
            outobj.q_term_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.q_term_min[a] = this.q_term_min[a];
            }
 
            outobj.q_term_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.q_term_max[a] = this.q_term_max[a];
            }
 
            outobj.qd_term_min = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.qd_term_min[a] = this.qd_term_min[a];
            }
 
            outobj.qd_term_max = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.qd_term_max[a] = this.qd_term_max[a];
            }
 
            outobj.r_term_min = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.r_term_min[a] = this.r_term_min[a];
            }
 
            outobj.r_term_max = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.r_term_max[a] = this.r_term_max[a];
            }
 
            outobj.rd_term_min = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.rd_term_min[a] = this.rd_term_min[a];
            }
 
            outobj.rd_term_max = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.rd_term_max[a] = this.rd_term_max[a];
            }
 
            outobj.h_term_min = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.h_term_min[a] = this.h_term_min[a];
            }
 
            outobj.h_term_max = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.h_term_max[a] = this.h_term_max[a];
            }
 
            outobj.Qq = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.Qq[a] = this.Qq[a];
            }
 
            outobj.Qv = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.Qv[a] = this.Qv[a];
            }
 
            outobj.Qr = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.Qr[a] = this.Qr[a];
            }
 
            outobj.Qh = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.Qh[a] = this.Qh[a];
            }
 
            outobj.Qc = new double[(int) NUM_LEGS_x3];
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                outobj.Qc[a] = this.Qc[a];
            }
 
            outobj.QNq = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.QNq[a] = this.QNq[a];
            }
 
            outobj.QNv = new double[(int) NUM_FB_DOF];
            for (int a = 0; a < this.NUM_FB_DOF; a++) {
                outobj.QNv[a] = this.QNv[a];
            }
 
            outobj.QNr = new double[(int) 6];
            for (int a = 0; a < 6; a++) {
                outobj.QNr[a] = this.QNr[a];
            }
 
            outobj.QNh = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.QNh[a] = this.QNh[a];
            }
 
            outobj.QNc = new double[(int) NUM_LEGS_x3];
            for (int a = 0; a < this.NUM_LEGS_x3; a++) {
                outobj.QNc[a] = this.QNc[a];
            }
 
            outobj.X_init_guess = new double[(int) NUM_OPT_VAR_TRAJ];
            for (int a = 0; a < this.NUM_OPT_VAR_TRAJ; a++) {
                outobj.X_init_guess[a] = this.X_init_guess[a];
            }
 
            outobj.lambdaG_init_guess = new double[(int) NUM_G_CONSTRAINTS];
            for (int a = 0; a < this.NUM_G_CONSTRAINTS; a++) {
                outobj.lambdaG_init_guess[a] = this.lambdaG_init_guess[a];
            }
 
            outobj.lambdaX_init_guess = new double[(int) NUM_X_CONSTRAINTS];
            for (int a = 0; a < this.NUM_X_CONSTRAINTS; a++) {
                outobj.lambdaX_init_guess[a] = this.lambdaX_init_guess[a];
            }
 
            outobj.Phi = new double[(int) NUM_GAIT_PHASE];
            for (int a = 0; a < this.NUM_GAIT_PHASE; a++) {
                outobj.Phi[a] = this.Phi[a];
            }
 
            return outobj;
        }
    }
}

