/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class spi_data_lcmt : LCM.LCM.LCMEncodable
    {
        public float[] q_abad;
        public float[] q_hip;
        public float[] q_knee;
        public float[] qd_abad;
        public float[] qd_hip;
        public float[] qd_knee;
        public int[] flags;
        public int spi_driver_status;
 
        public spi_data_lcmt()
        {
            q_abad = new float[4];
            q_hip = new float[4];
            q_knee = new float[4];
            qd_abad = new float[4];
            qd_hip = new float[4];
            qd_knee = new float[4];
            flags = new int[4];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x9d2fa835a926bf27L;
 
        static spi_data_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.spi_data_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.spi_data_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 4; a++) {
                outs.Write(this.q_abad[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.q_hip[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.q_knee[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.qd_abad[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.qd_hip[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.qd_knee[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.flags[a]); 
            }
 
            outs.Write(this.spi_driver_status); 
 
        }
 
        public spi_data_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public spi_data_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.spi_data_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.spi_data_lcmt o = new LCMTypes.spi_data_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.q_abad = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.q_abad[a] = ins.ReadSingle();
            }
 
            this.q_hip = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.q_hip[a] = ins.ReadSingle();
            }
 
            this.q_knee = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.q_knee[a] = ins.ReadSingle();
            }
 
            this.qd_abad = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.qd_abad[a] = ins.ReadSingle();
            }
 
            this.qd_hip = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.qd_hip[a] = ins.ReadSingle();
            }
 
            this.qd_knee = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.qd_knee[a] = ins.ReadSingle();
            }
 
            this.flags = new int[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.flags[a] = ins.ReadInt32();
            }
 
            this.spi_driver_status = ins.ReadInt32();
 
        }
 
        public LCMTypes.spi_data_lcmt Copy()
        {
            LCMTypes.spi_data_lcmt outobj = new LCMTypes.spi_data_lcmt();
            outobj.q_abad = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.q_abad[a] = this.q_abad[a];
            }
 
            outobj.q_hip = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.q_hip[a] = this.q_hip[a];
            }
 
            outobj.q_knee = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.q_knee[a] = this.q_knee[a];
            }
 
            outobj.qd_abad = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.qd_abad[a] = this.qd_abad[a];
            }
 
            outobj.qd_hip = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.qd_hip[a] = this.qd_hip[a];
            }
 
            outobj.qd_knee = new float[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.qd_knee[a] = this.qd_knee[a];
            }
 
            outobj.flags = new int[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.flags[a] = this.flags[a];
            }
 
            outobj.spi_driver_status = this.spi_driver_status;
 
            return outobj;
        }
    }
}

