/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) thd_G_dot_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};

/* thd_G_dot:(i0[2],i1[2],i2[2],i3[2])->(o0[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=6.;
  a2=1.6000000000000001e-03;
  a3=8.;
  a4=arg[0]? arg[0][1] : 0;
  a4=(a4/a1);
  a5=cos(a4);
  a5=(a3*a5);
  a6=arg[1]? arg[1][1] : 0;
  a7=sin(a6);
  a8=(a5*a7);
  a8=(a2*a8);
  a9=4.0000000000000002e-04;
  a10=57.;
  a11=arg[1]? arg[1][0] : 0;
  a12=cos(a11);
  a12=(a10*a12);
  a13=cos(a6);
  a14=(a12*a13);
  a14=(a9*a14);
  a8=(a8-a14);
  a14=7.;
  a15=sin(a11);
  a15=(a14*a15);
  a16=cos(a6);
  a17=(a15*a16);
  a17=(a2*a17);
  a8=(a8-a17);
  a17=cos(a11);
  a17=(a3*a17);
  a18=sin(a4);
  a19=(a17*a18);
  a20=cos(a6);
  a21=(a19*a20);
  a21=(a2*a21);
  a8=(a8-a21);
  a21=2.0000000000000001e-04;
  a22=49.;
  a23=sin(a11);
  a23=(a22*a23);
  a23=(a21*a23);
  a24=5.0000000000000002e-05;
  a25=399.;
  a26=cos(a11);
  a26=(a25*a26);
  a26=(a24*a26);
  a23=(a23-a26);
  a26=sin(a6);
  a27=sin(a11);
  a27=(a10*a27);
  a28=(a26*a27);
  a28=(a9*a28);
  a23=(a23+a28);
  a28=arg[0]? arg[0][0] : 0;
  a28=(a28/a1);
  a29=sin(a28);
  a29=(a14*a29);
  a30=cos(a11);
  a31=(a29*a30);
  a31=(a2*a31);
  a23=(a23-a31);
  a31=sin(a6);
  a32=cos(a11);
  a32=(a14*a32);
  a33=(a31*a32);
  a33=(a2*a33);
  a23=(a23+a33);
  a33=sin(a6);
  a34=sin(a28);
  a35=sin(a11);
  a35=(a3*a35);
  a36=(a34*a35);
  a37=(a33*a36);
  a37=(a2*a37);
  a23=(a23+a37);
  a37=(a23*a8);
  a38=cos(a28);
  a38=(a3*a38);
  a39=sin(a6);
  a40=(a38*a39);
  a40=(a2*a40);
  a41=cos(a11);
  a41=(a10*a41);
  a42=cos(a6);
  a43=(a41*a42);
  a43=(a9*a43);
  a40=(a40-a43);
  a43=sin(a11);
  a43=(a14*a43);
  a44=cos(a6);
  a45=(a43*a44);
  a45=(a2*a45);
  a40=(a40+a45);
  a45=cos(a11);
  a45=(a3*a45);
  a46=(a45*a34);
  a47=cos(a6);
  a48=(a46*a47);
  a48=(a2*a48);
  a40=(a40-a48);
  a48=sin(a11);
  a48=(a22*a48);
  a48=(a21*a48);
  a49=cos(a11);
  a49=(a25*a49);
  a49=(a24*a49);
  a48=(a48+a49);
  a49=sin(a6);
  a50=sin(a11);
  a50=(a10*a50);
  a51=(a49*a50);
  a51=(a9*a51);
  a48=(a48+a51);
  a51=sin(a4);
  a51=(a14*a51);
  a52=cos(a11);
  a53=(a51*a52);
  a53=(a2*a53);
  a48=(a48+a53);
  a53=sin(a6);
  a54=cos(a11);
  a54=(a14*a54);
  a55=(a53*a54);
  a55=(a2*a55);
  a48=(a48-a55);
  a55=sin(a6);
  a56=sin(a11);
  a56=(a3*a56);
  a57=(a18*a56);
  a58=(a55*a57);
  a58=(a2*a58);
  a48=(a48+a58);
  a58=(a40*a48);
  a37=(a37-a58);
  a58=(a8/a37);
  a59=cos(a6);
  a60=1.6666666666666666e-01;
  a61=cos(a28);
  a62=arg[2]? arg[2][0] : 0;
  a62=(a60*a62);
  a61=(a61*a62);
  a61=(a60*a61);
  a61=(a3*a61);
  a61=(a59*a61);
  a61=(a2*a61);
  a63=sin(a28);
  a63=(a63*a62);
  a63=(a60*a63);
  a63=(a10*a63);
  a63=(a9*a63);
  a61=(a61-a63);
  a63=sin(a11);
  a64=sin(a28);
  a64=(a64*a62);
  a64=(a60*a64);
  a64=(a14*a64);
  a64=(a63*a64);
  a64=(a2*a64);
  a61=(a61+a64);
  a64=sin(a28);
  a64=(a64*a62);
  a64=(a60*a64);
  a64=(a45*a64);
  a64=(a33*a64);
  a64=(a2*a64);
  a61=(a61+a64);
  a64=(a58*a61);
  a65=cos(a28);
  a65=(a60*a65);
  a65=(a10*a65);
  a65=(a9*a65);
  a66=sin(a28);
  a66=(a60*a66);
  a66=(a3*a66);
  a59=(a59*a66);
  a59=(a2*a59);
  a65=(a65+a59);
  a59=cos(a28);
  a59=(a60*a59);
  a59=(a14*a59);
  a63=(a63*a59);
  a63=(a2*a63);
  a65=(a65-a63);
  a63=cos(a28);
  a63=(a60*a63);
  a67=(a45*a63);
  a68=(a33*a67);
  a68=(a2*a68);
  a65=(a65-a68);
  a68=sin(a4);
  a69=arg[2]? arg[2][1] : 0;
  a69=(a60*a69);
  a68=(a68*a69);
  a68=(a3*a68);
  a7=(a7*a68);
  a7=(a2*a7);
  a68=cos(a4);
  a68=(a68*a69);
  a70=(a17*a68);
  a70=(a20*a70);
  a70=(a2*a70);
  a7=(a7+a70);
  a70=(a7/a37);
  a71=(a58/a37);
  a72=cos(a28);
  a72=(a72*a62);
  a35=(a35*a72);
  a35=(a33*a35);
  a35=(a2*a35);
  a73=cos(a28);
  a73=(a73*a62);
  a73=(a14*a73);
  a30=(a30*a73);
  a30=(a2*a30);
  a35=(a35-a30);
  a30=(a8*a35);
  a7=(a23*a7);
  a30=(a30-a7);
  a7=cos(a4);
  a7=(a7*a69);
  a7=(a14*a7);
  a52=(a52*a7);
  a52=(a2*a52);
  a56=(a56*a68);
  a56=(a55*a56);
  a56=(a2*a56);
  a52=(a52+a56);
  a56=(a40*a52);
  a28=sin(a28);
  a28=(a28*a62);
  a28=(a3*a28);
  a39=(a39*a28);
  a39=(a2*a39);
  a45=(a45*a72);
  a45=(a47*a45);
  a45=(a2*a45);
  a39=(a39+a45);
  a45=(a48*a39);
  a56=(a56-a45);
  a30=(a30-a56);
  a71=(a71*a30);
  a70=(a70+a71);
  a70=(a65*a70);
  a64=(a64-a70);
  a64=(a1*a64);
  a70=cos(a6);
  a71=arg[3]? arg[3][1] : 0;
  a70=(a70*a71);
  a5=(a5*a70);
  a5=(a2*a5);
  a70=sin(a11);
  a56=arg[3]? arg[3][0] : 0;
  a70=(a70*a56);
  a70=(a10*a70);
  a13=(a13*a70);
  a70=sin(a6);
  a70=(a70*a71);
  a12=(a12*a70);
  a13=(a13+a12);
  a13=(a9*a13);
  a5=(a5+a13);
  a13=cos(a11);
  a13=(a13*a56);
  a13=(a14*a13);
  a16=(a16*a13);
  a13=sin(a6);
  a13=(a13*a71);
  a15=(a15*a13);
  a16=(a16-a15);
  a16=(a2*a16);
  a5=(a5-a16);
  a16=sin(a11);
  a16=(a16*a56);
  a16=(a3*a16);
  a15=(a18*a16);
  a20=(a20*a15);
  a15=sin(a6);
  a15=(a15*a71);
  a19=(a19*a15);
  a20=(a20+a19);
  a20=(a2*a20);
  a5=(a5+a20);
  a20=(a5/a37);
  a19=(a58/a37);
  a15=cos(a11);
  a15=(a15*a56);
  a15=(a22*a15);
  a15=(a21*a15);
  a13=sin(a11);
  a13=(a13*a56);
  a13=(a25*a13);
  a13=(a24*a13);
  a15=(a15+a13);
  a13=cos(a6);
  a13=(a13*a71);
  a27=(a27*a13);
  a13=cos(a11);
  a13=(a13*a56);
  a13=(a10*a13);
  a26=(a26*a13);
  a27=(a27+a26);
  a27=(a9*a27);
  a15=(a15+a27);
  a27=sin(a11);
  a27=(a27*a56);
  a29=(a29*a27);
  a29=(a2*a29);
  a15=(a15+a29);
  a29=cos(a6);
  a29=(a29*a71);
  a32=(a32*a29);
  a29=sin(a11);
  a29=(a29*a56);
  a29=(a14*a29);
  a31=(a31*a29);
  a32=(a32-a31);
  a32=(a2*a32);
  a15=(a15+a32);
  a32=cos(a6);
  a32=(a32*a71);
  a36=(a36*a32);
  a31=cos(a11);
  a31=(a31*a56);
  a31=(a3*a31);
  a31=(a34*a31);
  a31=(a33*a31);
  a36=(a36+a31);
  a36=(a2*a36);
  a15=(a15+a36);
  a8=(a8*a15);
  a5=(a23*a5);
  a8=(a8+a5);
  a5=cos(a6);
  a5=(a5*a71);
  a38=(a38*a5);
  a38=(a2*a38);
  a5=sin(a11);
  a5=(a5*a56);
  a5=(a10*a5);
  a42=(a42*a5);
  a5=sin(a6);
  a5=(a5*a71);
  a41=(a41*a5);
  a42=(a42+a41);
  a42=(a9*a42);
  a38=(a38+a42);
  a42=cos(a11);
  a42=(a42*a56);
  a42=(a14*a42);
  a44=(a44*a42);
  a42=sin(a6);
  a42=(a42*a71);
  a43=(a43*a42);
  a44=(a44-a43);
  a44=(a2*a44);
  a38=(a38+a44);
  a44=sin(a11);
  a44=(a44*a56);
  a44=(a3*a44);
  a34=(a34*a44);
  a47=(a47*a34);
  a34=sin(a6);
  a34=(a34*a71);
  a46=(a46*a34);
  a47=(a47+a46);
  a47=(a2*a47);
  a38=(a38+a47);
  a47=(a48*a38);
  a46=cos(a11);
  a46=(a46*a56);
  a22=(a22*a46);
  a21=(a21*a22);
  a22=sin(a11);
  a22=(a22*a56);
  a25=(a25*a22);
  a24=(a24*a25);
  a21=(a21-a24);
  a24=cos(a6);
  a24=(a24*a71);
  a50=(a50*a24);
  a24=cos(a11);
  a24=(a24*a56);
  a24=(a10*a24);
  a49=(a49*a24);
  a50=(a50+a49);
  a50=(a9*a50);
  a21=(a21+a50);
  a50=sin(a11);
  a50=(a50*a56);
  a51=(a51*a50);
  a51=(a2*a51);
  a21=(a21-a51);
  a51=cos(a6);
  a51=(a51*a71);
  a54=(a54*a51);
  a51=sin(a11);
  a51=(a51*a56);
  a51=(a14*a51);
  a53=(a53*a51);
  a54=(a54-a53);
  a54=(a2*a54);
  a21=(a21-a54);
  a54=cos(a6);
  a54=(a54*a71);
  a57=(a57*a54);
  a53=cos(a11);
  a53=(a53*a56);
  a53=(a3*a53);
  a18=(a18*a53);
  a18=(a55*a18);
  a57=(a57+a18);
  a57=(a2*a57);
  a21=(a21+a57);
  a57=(a40*a21);
  a47=(a47+a57);
  a8=(a8-a47);
  a19=(a19*a8);
  a20=(a20-a19);
  a20=(a65*a20);
  a19=sin(a6);
  a19=(a19*a71);
  a66=(a66*a19);
  a66=(a2*a66);
  a19=cos(a11);
  a19=(a19*a56);
  a59=(a59*a19);
  a59=(a2*a59);
  a66=(a66+a59);
  a67=(a67*a32);
  a63=(a63*a44);
  a33=(a33*a63);
  a67=(a67-a33);
  a67=(a2*a67);
  a66=(a66+a67);
  a58=(a58*a66);
  a20=(a20-a58);
  a20=(a1*a20);
  a64=(a64+a20);
  a64=(-a64);
  if (res[0]!=0) res[0][2]=a64;
  a52=(a52/a37);
  a48=(a48/a37);
  a64=(a48/a37);
  a64=(a64*a30);
  a52=(a52-a64);
  a52=(a65*a52);
  a61=(a48*a61);
  a52=(a52+a61);
  a52=(a1*a52);
  a21=(a21/a37);
  a61=(a48/a37);
  a61=(a61*a8);
  a21=(a21-a61);
  a65=(a65*a21);
  a48=(a48*a66);
  a65=(a65-a48);
  a65=(a1*a65);
  a52=(a52+a65);
  if (res[0]!=0) res[0][3]=a52;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a40=(a40/a37);
  a0=cos(a6);
  a52=cos(a4);
  a52=(a52*a69);
  a52=(a60*a52);
  a52=(a3*a52);
  a52=(a0*a52);
  a52=(a2*a52);
  a65=sin(a4);
  a65=(a65*a69);
  a65=(a60*a65);
  a65=(a10*a65);
  a65=(a9*a65);
  a52=(a52-a65);
  a65=sin(a11);
  a48=sin(a4);
  a48=(a48*a69);
  a48=(a60*a48);
  a48=(a14*a48);
  a48=(a65*a48);
  a48=(a2*a48);
  a52=(a52-a48);
  a48=sin(a4);
  a48=(a48*a69);
  a48=(a60*a48);
  a48=(a17*a48);
  a48=(a55*a48);
  a48=(a2*a48);
  a52=(a52+a48);
  a48=(a40*a52);
  a69=cos(a4);
  a69=(a60*a69);
  a10=(a10*a69);
  a9=(a9*a10);
  a10=sin(a4);
  a10=(a60*a10);
  a3=(a3*a10);
  a0=(a0*a3);
  a0=(a2*a0);
  a9=(a9+a0);
  a0=cos(a4);
  a0=(a60*a0);
  a14=(a14*a0);
  a65=(a65*a14);
  a65=(a2*a65);
  a9=(a9+a65);
  a4=cos(a4);
  a60=(a60*a4);
  a17=(a17*a60);
  a4=(a55*a17);
  a4=(a2*a4);
  a9=(a9-a4);
  a39=(a39/a37);
  a4=(a40/a37);
  a4=(a4*a30);
  a39=(a39+a4);
  a39=(a9*a39);
  a48=(a48-a39);
  a48=(a1*a48);
  a38=(a38/a37);
  a39=(a40/a37);
  a39=(a39*a8);
  a38=(a38-a39);
  a38=(a9*a38);
  a11=cos(a11);
  a11=(a11*a56);
  a14=(a14*a11);
  a14=(a2*a14);
  a6=sin(a6);
  a6=(a6*a71);
  a3=(a3*a6);
  a3=(a2*a3);
  a14=(a14-a3);
  a17=(a17*a54);
  a60=(a60*a16);
  a55=(a55*a60);
  a17=(a17-a55);
  a2=(a2*a17);
  a14=(a14-a2);
  a40=(a40*a14);
  a38=(a38+a40);
  a38=(a1*a38);
  a48=(a48+a38);
  if (res[0]!=0) res[0][6]=a48;
  a35=(a35/a37);
  a23=(a23/a37);
  a48=(a23/a37);
  a48=(a48*a30);
  a35=(a35-a48);
  a35=(a9*a35);
  a52=(a23*a52);
  a35=(a35+a52);
  a35=(a1*a35);
  a15=(a15/a37);
  a37=(a23/a37);
  a37=(a37*a8);
  a15=(a15-a37);
  a9=(a9*a15);
  a23=(a23*a14);
  a9=(a9+a23);
  a1=(a1*a9);
  a35=(a35+a1);
  a35=(-a35);
  if (res[0]!=0) res[0][7]=a35;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int thd_G_dot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int thd_G_dot_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int thd_G_dot_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void thd_G_dot_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int thd_G_dot_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void thd_G_dot_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void thd_G_dot_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void thd_G_dot_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int thd_G_dot_n_in(void) { return 4;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int thd_G_dot_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real thd_G_dot_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* thd_G_dot_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* thd_G_dot_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* thd_G_dot_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* thd_G_dot_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int thd_G_dot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


