/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) thd_IK_vel_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};

/* thd_IK_vel:(i0[2],i1[2])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a4, a5, a6, a7, a8, a9;
  a0=2.2800000000000001e-02;
  a1=8.;
  a2=arg[0]? arg[0][0] : 0;
  a3=cos(a2);
  a3=(a1*a3);
  a4=arg[0]? arg[0][1] : 0;
  a5=sin(a4);
  a6=(a3*a5);
  a7=625.;
  a6=(a6/a7);
  a6=(a0-a6);
  a8=7.;
  a9=sin(a2);
  a9=(a8*a9);
  a9=(a9/a7);
  a6=(a6-a9);
  a9=casadi_sq(a6);
  a10=cos(a4);
  a10=(a1*a10);
  a10=(a10/a7);
  a11=casadi_sq(a10);
  a9=(a9+a11);
  a11=49.;
  a12=cos(a2);
  a12=(a11*a12);
  a13=5000.;
  a12=(a12/a13);
  a14=399.;
  a15=sin(a2);
  a15=(a14*a15);
  a16=20000.;
  a15=(a15/a16);
  a12=(a12+a15);
  a15=57.;
  a17=cos(a2);
  a17=(a15*a17);
  a18=sin(a4);
  a19=(a17*a18);
  a20=2500.;
  a19=(a19/a20);
  a12=(a12+a19);
  a19=sin(a2);
  a19=(a8*a19);
  a21=sin(a4);
  a22=(a19*a21);
  a22=(a22/a7);
  a12=(a12-a22);
  a22=1.8881249999999999e-02;
  a12=(a12-a22);
  a23=casadi_sq(a12);
  a9=(a9-a23);
  a9=sqrt(a9);
  a23=(a6*a9);
  a24=(a10*a12);
  a23=(a23-a24);
  a24=(a10*a9);
  a25=(a6*a12);
  a24=(a24+a25);
  a25=casadi_sq(a24);
  a26=casadi_sq(a23);
  a25=(a25+a26);
  a23=(a23/a25);
  a26=5.0000000000000002e-05;
  a27=cos(a2);
  a28=arg[1]? arg[1][0] : 0;
  a27=(a27*a28);
  a27=(a14*a27);
  a27=(a26*a27);
  a29=2.0000000000000001e-04;
  a30=sin(a2);
  a30=(a30*a28);
  a30=(a11*a30);
  a30=(a29*a30);
  a27=(a27-a30);
  a30=4.0000000000000002e-04;
  a31=cos(a4);
  a32=arg[1]? arg[1][1] : 0;
  a31=(a31*a32);
  a17=(a17*a31);
  a31=sin(a2);
  a31=(a31*a28);
  a31=(a15*a31);
  a18=(a18*a31);
  a17=(a17-a18);
  a17=(a30*a17);
  a27=(a27+a17);
  a17=1.6000000000000001e-03;
  a18=cos(a2);
  a18=(a18*a28);
  a18=(a8*a18);
  a21=(a21*a18);
  a18=cos(a4);
  a18=(a18*a32);
  a19=(a19*a18);
  a21=(a21+a19);
  a21=(a17*a21);
  a27=(a27-a21);
  a21=(a6*a27);
  a19=cos(a4);
  a19=(a19*a32);
  a3=(a3*a19);
  a19=sin(a2);
  a19=(a19*a28);
  a19=(a1*a19);
  a5=(a5*a19);
  a3=(a3-a5);
  a3=(a17*a3);
  a5=cos(a2);
  a5=(a5*a28);
  a5=(a8*a5);
  a5=(a17*a5);
  a3=(a3+a5);
  a5=(a12*a3);
  a21=(a21-a5);
  a5=sin(a4);
  a5=(a5*a32);
  a5=(a1*a5);
  a5=(a17*a5);
  a19=(a9*a5);
  a18=(a6+a6);
  a18=(a18*a3);
  a31=(a10+a10);
  a31=(a31*a5);
  a18=(a18+a31);
  a31=(a12+a12);
  a31=(a31*a27);
  a18=(a18+a31);
  a31=(a9+a9);
  a18=(a18/a31);
  a31=(a10*a18);
  a19=(a19+a31);
  a21=(a21-a19);
  a23=(a23*a21);
  a24=(a24/a25);
  a9=(a9*a3);
  a6=(a6*a18);
  a9=(a9+a6);
  a10=(a10*a27);
  a12=(a12*a5);
  a10=(a10-a12);
  a9=(a9+a10);
  a24=(a24*a9);
  a23=(a23+a24);
  if (res[0]!=0) res[0][0]=a23;
  a23=sin(a2);
  a23=(a8*a23);
  a23=(a23/a7);
  a24=cos(a2);
  a24=(a1*a24);
  a9=sin(a4);
  a10=(a24*a9);
  a10=(a10/a7);
  a23=(a23-a10);
  a23=(a23+a0);
  a0=casadi_sq(a23);
  a10=cos(a4);
  a10=(a1*a10);
  a10=(a10/a7);
  a12=casadi_sq(a10);
  a0=(a0+a12);
  a12=cos(a2);
  a12=(a11*a12);
  a12=(a12/a13);
  a13=sin(a2);
  a13=(a14*a13);
  a13=(a13/a16);
  a12=(a12-a13);
  a13=cos(a2);
  a13=(a15*a13);
  a16=sin(a4);
  a5=(a13*a16);
  a5=(a5/a20);
  a12=(a12+a5);
  a5=sin(a2);
  a5=(a8*a5);
  a20=sin(a4);
  a27=(a5*a20);
  a27=(a27/a7);
  a12=(a12+a27);
  a12=(a12-a22);
  a22=casadi_sq(a12);
  a0=(a0-a22);
  a0=sqrt(a0);
  a22=(a23*a0);
  a27=(a10*a12);
  a22=(a22-a27);
  a27=(a10*a0);
  a7=(a23*a12);
  a27=(a27+a7);
  a7=casadi_sq(a27);
  a6=casadi_sq(a22);
  a7=(a7+a6);
  a22=(a22/a7);
  a6=(a23+a23);
  a18=cos(a2);
  a18=(a18*a28);
  a18=(a8*a18);
  a18=(a17*a18);
  a3=cos(a4);
  a3=(a3*a32);
  a24=(a24*a3);
  a3=sin(a2);
  a3=(a3*a28);
  a3=(a1*a3);
  a9=(a9*a3);
  a24=(a24-a9);
  a24=(a17*a24);
  a18=(a18-a24);
  a6=(a6*a18);
  a24=(a10+a10);
  a9=sin(a4);
  a9=(a9*a32);
  a1=(a1*a9);
  a1=(a17*a1);
  a24=(a24*a1);
  a6=(a6-a24);
  a24=(a12+a12);
  a9=cos(a4);
  a9=(a9*a32);
  a13=(a13*a9);
  a9=sin(a2);
  a9=(a9*a28);
  a15=(a15*a9);
  a16=(a16*a15);
  a13=(a13-a16);
  a30=(a30*a13);
  a13=sin(a2);
  a13=(a13*a28);
  a11=(a11*a13);
  a29=(a29*a11);
  a11=cos(a2);
  a11=(a11*a28);
  a14=(a14*a11);
  a26=(a26*a14);
  a29=(a29+a26);
  a30=(a30-a29);
  a2=cos(a2);
  a2=(a2*a28);
  a8=(a8*a2);
  a20=(a20*a8);
  a4=cos(a4);
  a4=(a4*a32);
  a5=(a5*a4);
  a20=(a20+a5);
  a17=(a17*a20);
  a30=(a30+a17);
  a24=(a24*a30);
  a6=(a6-a24);
  a24=(a0+a0);
  a6=(a6/a24);
  a24=(a10*a6);
  a17=(a0*a1);
  a24=(a24-a17);
  a17=(a12*a18);
  a20=(a23*a30);
  a17=(a17+a20);
  a24=(a24+a17);
  a22=(a22*a24);
  a27=(a27/a7);
  a0=(a0*a18);
  a23=(a23*a6);
  a0=(a0+a23);
  a10=(a10*a30);
  a12=(a12*a1);
  a10=(a10-a12);
  a0=(a0-a10);
  a27=(a27*a0);
  a22=(a22-a27);
  if (res[0]!=0) res[0][1]=a22;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int thd_IK_vel(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int thd_IK_vel_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int thd_IK_vel_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void thd_IK_vel_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int thd_IK_vel_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void thd_IK_vel_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void thd_IK_vel_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void thd_IK_vel_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int thd_IK_vel_n_in(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int thd_IK_vel_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real thd_IK_vel_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* thd_IK_vel_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* thd_IK_vel_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* thd_IK_vel_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* thd_IK_vel_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int thd_IK_vel_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


