#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
GRBDA_DIR=$DIR/../
cd $GRBDA_DIR
echo $GRBDA_DIR
sudo docker build . -t grbda-docker  -f $GRBDA_DIR/grbda-docker/Dockerfile
