<?xml version="1.0"?>

<robot name="variable_revolute_rotor_pair_branch" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="branch_count" default="4"/>
    <xacro:arg name="depth_count" default="3"/>
    <xacro:property name="branch_count" value="$(arg branch_count)"/>
    <xacro:property name="depth_count" value="$(arg depth_count)"/>
    <xacro:property name="i" value="0"/>
    <xacro:include filename="revolute_rotor_pair_properties.xacro"/>

    <xacro:macro name="build_revolute_rotor_pair_series_chain_at_each_branch" params="branch_count depth_count i">
        <xacro:if value="${branch_count - i}">
            <xacro:if value="${depth_count - 1}">
                <xacro:nonsequential_revolute_rotor_pair_serial_chain
                    parent_link_idx="${2 * (branch_count - i)}"
                    first_child_link_idx="${2 * branch_count + 2 * (branch_count - 1) * (depth_count - 1) + 1
                                        - i * 2 * (depth_count - 1)}"
                    count="${depth_count}"/>

                <xacro:build_revolute_rotor_pair_series_chain_at_each_branch branch_count="${branch_count}"
                                                        depth_count="${depth_count}"
                                                        i="${i + 1}"/>
            </xacro:if>
        </xacro:if>
    </xacro:macro>

    <link name="base"/>
    <xacro:revolute_rotor_pair_root_branch branch_count="${branch_count}"/>
    <xacro:build_revolute_rotor_pair_series_chain_at_each_branch branch_count="${branch_count}"
                                             depth_count="${depth_count}"
                                             i="${i}"/>

</robot>