"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class basic_jump_info_lcmt(object):
    __slots__ = ["height_delta", "dist_to_obst"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.height_delta = 0.0
        self.dist_to_obst = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(basic_jump_info_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.height_delta, self.dist_to_obst))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != basic_jump_info_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return basic_jump_info_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = basic_jump_info_lcmt()
        self.height_delta, self.dist_to_obst = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if basic_jump_info_lcmt in parents: return 0
        tmphash = (0xa5b0ac89c048c7a1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if basic_jump_info_lcmt._packed_fingerprint is None:
            basic_jump_info_lcmt._packed_fingerprint = struct.pack(">Q", basic_jump_info_lcmt._get_hash_recursive([]))
        return basic_jump_info_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

