"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class humanoid_data_lcmt(object):
    __slots__ = ["q_hipz", "q_hipx", "q_hipy", "q_knee", "q_ankle", "q_shouldery", "q_shoulderx", "q_shoulderz", "q_elbow", "qd_hipz", "qd_hipx", "qd_hipy", "qd_knee", "qd_ankle", "qd_shouldery", "qd_shoulderx", "qd_shoulderz", "qd_elbow", "tau_hipz", "tau_hipx", "tau_hipy", "tau_knee", "tau_ankle", "tau_shouldery", "tau_shoulderx", "tau_shoulderz", "tau_elbow", "flags", "spi_driver_status"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "int32_t", "int32_t"]

    __dimensions__ = [[2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [6], None]

    def __init__(self):
        self.q_hipz = [ 0.0 for dim0 in range(2) ]
        self.q_hipx = [ 0.0 for dim0 in range(2) ]
        self.q_hipy = [ 0.0 for dim0 in range(2) ]
        self.q_knee = [ 0.0 for dim0 in range(2) ]
        self.q_ankle = [ 0.0 for dim0 in range(2) ]
        self.q_shouldery = [ 0.0 for dim0 in range(2) ]
        self.q_shoulderx = [ 0.0 for dim0 in range(2) ]
        self.q_shoulderz = [ 0.0 for dim0 in range(2) ]
        self.q_elbow = [ 0.0 for dim0 in range(2) ]
        self.qd_hipz = [ 0.0 for dim0 in range(2) ]
        self.qd_hipx = [ 0.0 for dim0 in range(2) ]
        self.qd_hipy = [ 0.0 for dim0 in range(2) ]
        self.qd_knee = [ 0.0 for dim0 in range(2) ]
        self.qd_ankle = [ 0.0 for dim0 in range(2) ]
        self.qd_shouldery = [ 0.0 for dim0 in range(2) ]
        self.qd_shoulderx = [ 0.0 for dim0 in range(2) ]
        self.qd_shoulderz = [ 0.0 for dim0 in range(2) ]
        self.qd_elbow = [ 0.0 for dim0 in range(2) ]
        self.tau_hipz = [ 0.0 for dim0 in range(2) ]
        self.tau_hipx = [ 0.0 for dim0 in range(2) ]
        self.tau_hipy = [ 0.0 for dim0 in range(2) ]
        self.tau_knee = [ 0.0 for dim0 in range(2) ]
        self.tau_ankle = [ 0.0 for dim0 in range(2) ]
        self.tau_shouldery = [ 0.0 for dim0 in range(2) ]
        self.tau_shoulderx = [ 0.0 for dim0 in range(2) ]
        self.tau_shoulderz = [ 0.0 for dim0 in range(2) ]
        self.tau_elbow = [ 0.0 for dim0 in range(2) ]
        self.flags = [ 0 for dim0 in range(6) ]
        self.spi_driver_status = 0

    def encode(self):
        buf = BytesIO()
        buf.write(humanoid_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2f', *self.q_hipz[:2]))
        buf.write(struct.pack('>2f', *self.q_hipx[:2]))
        buf.write(struct.pack('>2f', *self.q_hipy[:2]))
        buf.write(struct.pack('>2f', *self.q_knee[:2]))
        buf.write(struct.pack('>2f', *self.q_ankle[:2]))
        buf.write(struct.pack('>2f', *self.q_shouldery[:2]))
        buf.write(struct.pack('>2f', *self.q_shoulderx[:2]))
        buf.write(struct.pack('>2f', *self.q_shoulderz[:2]))
        buf.write(struct.pack('>2f', *self.q_elbow[:2]))
        buf.write(struct.pack('>2f', *self.qd_hipz[:2]))
        buf.write(struct.pack('>2f', *self.qd_hipx[:2]))
        buf.write(struct.pack('>2f', *self.qd_hipy[:2]))
        buf.write(struct.pack('>2f', *self.qd_knee[:2]))
        buf.write(struct.pack('>2f', *self.qd_ankle[:2]))
        buf.write(struct.pack('>2f', *self.qd_shouldery[:2]))
        buf.write(struct.pack('>2f', *self.qd_shoulderx[:2]))
        buf.write(struct.pack('>2f', *self.qd_shoulderz[:2]))
        buf.write(struct.pack('>2f', *self.qd_elbow[:2]))
        buf.write(struct.pack('>2f', *self.tau_hipz[:2]))
        buf.write(struct.pack('>2f', *self.tau_hipx[:2]))
        buf.write(struct.pack('>2f', *self.tau_hipy[:2]))
        buf.write(struct.pack('>2f', *self.tau_knee[:2]))
        buf.write(struct.pack('>2f', *self.tau_ankle[:2]))
        buf.write(struct.pack('>2f', *self.tau_shouldery[:2]))
        buf.write(struct.pack('>2f', *self.tau_shoulderx[:2]))
        buf.write(struct.pack('>2f', *self.tau_shoulderz[:2]))
        buf.write(struct.pack('>2f', *self.tau_elbow[:2]))
        buf.write(struct.pack('>6i', *self.flags[:6]))
        buf.write(struct.pack(">i", self.spi_driver_status))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != humanoid_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return humanoid_data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = humanoid_data_lcmt()
        self.q_hipz = struct.unpack('>2f', buf.read(8))
        self.q_hipx = struct.unpack('>2f', buf.read(8))
        self.q_hipy = struct.unpack('>2f', buf.read(8))
        self.q_knee = struct.unpack('>2f', buf.read(8))
        self.q_ankle = struct.unpack('>2f', buf.read(8))
        self.q_shouldery = struct.unpack('>2f', buf.read(8))
        self.q_shoulderx = struct.unpack('>2f', buf.read(8))
        self.q_shoulderz = struct.unpack('>2f', buf.read(8))
        self.q_elbow = struct.unpack('>2f', buf.read(8))
        self.qd_hipz = struct.unpack('>2f', buf.read(8))
        self.qd_hipx = struct.unpack('>2f', buf.read(8))
        self.qd_hipy = struct.unpack('>2f', buf.read(8))
        self.qd_knee = struct.unpack('>2f', buf.read(8))
        self.qd_ankle = struct.unpack('>2f', buf.read(8))
        self.qd_shouldery = struct.unpack('>2f', buf.read(8))
        self.qd_shoulderx = struct.unpack('>2f', buf.read(8))
        self.qd_shoulderz = struct.unpack('>2f', buf.read(8))
        self.qd_elbow = struct.unpack('>2f', buf.read(8))
        self.tau_hipz = struct.unpack('>2f', buf.read(8))
        self.tau_hipx = struct.unpack('>2f', buf.read(8))
        self.tau_hipy = struct.unpack('>2f', buf.read(8))
        self.tau_knee = struct.unpack('>2f', buf.read(8))
        self.tau_ankle = struct.unpack('>2f', buf.read(8))
        self.tau_shouldery = struct.unpack('>2f', buf.read(8))
        self.tau_shoulderx = struct.unpack('>2f', buf.read(8))
        self.tau_shoulderz = struct.unpack('>2f', buf.read(8))
        self.tau_elbow = struct.unpack('>2f', buf.read(8))
        self.flags = struct.unpack('>6i', buf.read(24))
        self.spi_driver_status = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if humanoid_data_lcmt in parents: return 0
        tmphash = (0x92fdd14e5ce4ce) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if humanoid_data_lcmt._packed_fingerprint is None:
            humanoid_data_lcmt._packed_fingerprint = struct.pack(">Q", humanoid_data_lcmt._get_hash_recursive([]))
        return humanoid_data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

