"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mcvision_state_info_lcmt(object):
    __slots__ = ["body_pos", "body_ori_quat_visual", "body_ori_quat_est", "jpos"]

    __typenames__ = ["float", "float", "float", "float"]

    __dimensions__ = [[3], [4], [4], [12]]

    def __init__(self):
        self.body_pos = [ 0.0 for dim0 in range(3) ]
        self.body_ori_quat_visual = [ 0.0 for dim0 in range(4) ]
        self.body_ori_quat_est = [ 0.0 for dim0 in range(4) ]
        self.jpos = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(mcvision_state_info_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.body_pos[:3]))
        buf.write(struct.pack('>4f', *self.body_ori_quat_visual[:4]))
        buf.write(struct.pack('>4f', *self.body_ori_quat_est[:4]))
        buf.write(struct.pack('>12f', *self.jpos[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mcvision_state_info_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mcvision_state_info_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mcvision_state_info_lcmt()
        self.body_pos = struct.unpack('>3f', buf.read(12))
        self.body_ori_quat_visual = struct.unpack('>4f', buf.read(16))
        self.body_ori_quat_est = struct.unpack('>4f', buf.read(16))
        self.jpos = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if mcvision_state_info_lcmt in parents: return 0
        tmphash = (0x1b2eb82c13b66874) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mcvision_state_info_lcmt._packed_fingerprint is None:
            mcvision_state_info_lcmt._packed_fingerprint = struct.pack(">Q", mcvision_state_info_lcmt._get_hash_recursive([]))
        return mcvision_state_info_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

