"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class tello_command_lcmt(object):
    __slots__ = ["q_des_hipz", "q_des_hipx", "q_des_hipy", "q_des_knee", "q_des_ankle", "qd_des_hipz", "qd_des_hipx", "qd_des_hipy", "qd_des_knee", "qd_des_ankle", "kp_hipz", "kp_hipx", "kp_hipy", "kp_knee", "kp_ankle", "kd_hipz", "kd_hipx", "kd_hipy", "kd_knee", "kd_ankle", "tau_hipz_ff", "tau_hipx_ff", "tau_hipy_ff", "tau_knee_ff", "tau_ankle_ff", "flags"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "int32_t"]

    __dimensions__ = [[2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [2], [4]]

    def __init__(self):
        self.q_des_hipz = [ 0.0 for dim0 in range(2) ]
        self.q_des_hipx = [ 0.0 for dim0 in range(2) ]
        self.q_des_hipy = [ 0.0 for dim0 in range(2) ]
        self.q_des_knee = [ 0.0 for dim0 in range(2) ]
        self.q_des_ankle = [ 0.0 for dim0 in range(2) ]
        self.qd_des_hipz = [ 0.0 for dim0 in range(2) ]
        self.qd_des_hipx = [ 0.0 for dim0 in range(2) ]
        self.qd_des_hipy = [ 0.0 for dim0 in range(2) ]
        self.qd_des_knee = [ 0.0 for dim0 in range(2) ]
        self.qd_des_ankle = [ 0.0 for dim0 in range(2) ]
        self.kp_hipz = [ 0.0 for dim0 in range(2) ]
        self.kp_hipx = [ 0.0 for dim0 in range(2) ]
        self.kp_hipy = [ 0.0 for dim0 in range(2) ]
        self.kp_knee = [ 0.0 for dim0 in range(2) ]
        self.kp_ankle = [ 0.0 for dim0 in range(2) ]
        self.kd_hipz = [ 0.0 for dim0 in range(2) ]
        self.kd_hipx = [ 0.0 for dim0 in range(2) ]
        self.kd_hipy = [ 0.0 for dim0 in range(2) ]
        self.kd_knee = [ 0.0 for dim0 in range(2) ]
        self.kd_ankle = [ 0.0 for dim0 in range(2) ]
        self.tau_hipz_ff = [ 0.0 for dim0 in range(2) ]
        self.tau_hipx_ff = [ 0.0 for dim0 in range(2) ]
        self.tau_hipy_ff = [ 0.0 for dim0 in range(2) ]
        self.tau_knee_ff = [ 0.0 for dim0 in range(2) ]
        self.tau_ankle_ff = [ 0.0 for dim0 in range(2) ]
        self.flags = [ 0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(tello_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2f', *self.q_des_hipz[:2]))
        buf.write(struct.pack('>2f', *self.q_des_hipx[:2]))
        buf.write(struct.pack('>2f', *self.q_des_hipy[:2]))
        buf.write(struct.pack('>2f', *self.q_des_knee[:2]))
        buf.write(struct.pack('>2f', *self.q_des_ankle[:2]))
        buf.write(struct.pack('>2f', *self.qd_des_hipz[:2]))
        buf.write(struct.pack('>2f', *self.qd_des_hipx[:2]))
        buf.write(struct.pack('>2f', *self.qd_des_hipy[:2]))
        buf.write(struct.pack('>2f', *self.qd_des_knee[:2]))
        buf.write(struct.pack('>2f', *self.qd_des_ankle[:2]))
        buf.write(struct.pack('>2f', *self.kp_hipz[:2]))
        buf.write(struct.pack('>2f', *self.kp_hipx[:2]))
        buf.write(struct.pack('>2f', *self.kp_hipy[:2]))
        buf.write(struct.pack('>2f', *self.kp_knee[:2]))
        buf.write(struct.pack('>2f', *self.kp_ankle[:2]))
        buf.write(struct.pack('>2f', *self.kd_hipz[:2]))
        buf.write(struct.pack('>2f', *self.kd_hipx[:2]))
        buf.write(struct.pack('>2f', *self.kd_hipy[:2]))
        buf.write(struct.pack('>2f', *self.kd_knee[:2]))
        buf.write(struct.pack('>2f', *self.kd_ankle[:2]))
        buf.write(struct.pack('>2f', *self.tau_hipz_ff[:2]))
        buf.write(struct.pack('>2f', *self.tau_hipx_ff[:2]))
        buf.write(struct.pack('>2f', *self.tau_hipy_ff[:2]))
        buf.write(struct.pack('>2f', *self.tau_knee_ff[:2]))
        buf.write(struct.pack('>2f', *self.tau_ankle_ff[:2]))
        buf.write(struct.pack('>4i', *self.flags[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != tello_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tello_command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tello_command_lcmt()
        self.q_des_hipz = struct.unpack('>2f', buf.read(8))
        self.q_des_hipx = struct.unpack('>2f', buf.read(8))
        self.q_des_hipy = struct.unpack('>2f', buf.read(8))
        self.q_des_knee = struct.unpack('>2f', buf.read(8))
        self.q_des_ankle = struct.unpack('>2f', buf.read(8))
        self.qd_des_hipz = struct.unpack('>2f', buf.read(8))
        self.qd_des_hipx = struct.unpack('>2f', buf.read(8))
        self.qd_des_hipy = struct.unpack('>2f', buf.read(8))
        self.qd_des_knee = struct.unpack('>2f', buf.read(8))
        self.qd_des_ankle = struct.unpack('>2f', buf.read(8))
        self.kp_hipz = struct.unpack('>2f', buf.read(8))
        self.kp_hipx = struct.unpack('>2f', buf.read(8))
        self.kp_hipy = struct.unpack('>2f', buf.read(8))
        self.kp_knee = struct.unpack('>2f', buf.read(8))
        self.kp_ankle = struct.unpack('>2f', buf.read(8))
        self.kd_hipz = struct.unpack('>2f', buf.read(8))
        self.kd_hipx = struct.unpack('>2f', buf.read(8))
        self.kd_hipy = struct.unpack('>2f', buf.read(8))
        self.kd_knee = struct.unpack('>2f', buf.read(8))
        self.kd_ankle = struct.unpack('>2f', buf.read(8))
        self.tau_hipz_ff = struct.unpack('>2f', buf.read(8))
        self.tau_hipx_ff = struct.unpack('>2f', buf.read(8))
        self.tau_hipy_ff = struct.unpack('>2f', buf.read(8))
        self.tau_knee_ff = struct.unpack('>2f', buf.read(8))
        self.tau_ankle_ff = struct.unpack('>2f', buf.read(8))
        self.flags = struct.unpack('>4i', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tello_command_lcmt in parents: return 0
        tmphash = (0x11e6adc393f0b759) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tello_command_lcmt._packed_fingerprint is None:
            tello_command_lcmt._packed_fingerprint = struct.pack(">Q", tello_command_lcmt._get_hash_recursive([]))
        return tello_command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

