/* This file was automatically generated by CasADi 3.6.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tkad_G_dot_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};

/* tkad_G_dot:(i0[2],i1[2],i2[2],i3[2])->(o0[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=4.0000000000000002e-04;
  a2=7.;
  a3=5.0000000000000000e-01;
  a4=arg[0]? arg[0][0] : 0;
  a5=2.;
  a6=(a4/a5);
  a7=arg[0]? arg[0][1] : 0;
  a8=(a7/a5);
  a6=(a6-a8);
  a8=arg[1]? arg[1][1] : 0;
  a6=(a6+a8);
  a9=1.4514158059584845e+00;
  a6=(a6+a9);
  a9=sin(a6);
  a10=arg[3]? arg[3][1] : 0;
  a9=(a9*a10);
  a11=(a3*a9);
  a11=(a2*a11);
  a11=(a1*a11);
  a12=2.0000000000000001e-04;
  a13=91.;
  a14=4.1887902047863906e-01;
  a14=(a8+a14);
  a15=cos(a14);
  a15=(a13*a15);
  a15=(a12*a15);
  a16=cos(a6);
  a16=(a2*a16);
  a16=(a1*a16);
  a15=(a15-a16);
  a16=2.0000000000000002e-05;
  a17=147.;
  a18=6.9813170079773182e-02;
  a8=(a8+a18);
  a18=cos(a8);
  a18=(a17*a18);
  a18=(a16*a18);
  a15=(a15-a18);
  a11=(a11/a15);
  a18=1.6000000000000001e-03;
  a19=13.;
  a20=(a4/a5);
  a21=(a7/a5);
  a20=(a20-a21);
  a21=1.0325367854798453e+00;
  a20=(a20+a21);
  a21=sin(a20);
  a22=(a3*a21);
  a22=(a19*a22);
  a22=(a18*a22);
  a23=1.6000000000000001e-04;
  a24=21.;
  a4=(a4/a5);
  a7=(a7/a5);
  a4=(a4-a7);
  a7=1.3816026358787112e+00;
  a4=(a4+a7);
  a7=sin(a4);
  a5=(a3*a7);
  a5=(a24*a5);
  a5=(a23*a5);
  a22=(a22-a5);
  a5=cos(a6);
  a25=(a3*a5);
  a25=(a2*a25);
  a25=(a1*a25);
  a22=(a22-a25);
  a22=(a22/a15);
  a25=(a22/a15);
  a26=sin(a6);
  a26=(a26*a10);
  a26=(a2*a26);
  a26=(a1*a26);
  a14=sin(a14);
  a14=(a14*a10);
  a13=(a13*a14);
  a12=(a12*a13);
  a26=(a26-a12);
  a8=sin(a8);
  a8=(a8*a10);
  a17=(a17*a8);
  a16=(a16*a17);
  a26=(a26+a16);
  a25=(a25*a26);
  a11=(a11-a25);
  a20=cos(a20);
  a25=arg[2]? arg[2][0] : 0;
  a16=(a3*a25);
  a17=arg[2]? arg[2][1] : 0;
  a8=(a3*a17);
  a16=(a16-a8);
  a20=(a20*a16);
  a16=(a3*a20);
  a16=(a19*a16);
  a16=(a18*a16);
  a4=cos(a4);
  a8=(a3*a25);
  a10=(a3*a17);
  a8=(a8-a10);
  a4=(a4*a8);
  a8=(a3*a4);
  a8=(a24*a8);
  a8=(a23*a8);
  a16=(a16-a8);
  a8=sin(a6);
  a25=(a3*a25);
  a17=(a3*a17);
  a25=(a25-a17);
  a8=(a8*a25);
  a3=(a3*a8);
  a3=(a2*a3);
  a3=(a1*a3);
  a16=(a16+a3);
  a16=(a16/a15);
  a22=(a22/a15);
  a6=sin(a6);
  a6=(a6*a25);
  a6=(a2*a6);
  a6=(a1*a6);
  a22=(a22*a6);
  a16=(a16-a22);
  a11=(a11+a16);
  a11=(-a11);
  if (res[0]!=0) res[0][3]=a11;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  a0=-5.0000000000000000e-01;
  a9=(a0*a9);
  a9=(a2*a9);
  a9=(a1*a9);
  a9=(a9/a15);
  a21=(a0*a21);
  a21=(a19*a21);
  a21=(a18*a21);
  a7=(a0*a7);
  a7=(a24*a7);
  a7=(a23*a7);
  a21=(a21-a7);
  a5=(a0*a5);
  a5=(a2*a5);
  a5=(a1*a5);
  a21=(a21-a5);
  a21=(a21/a15);
  a5=(a21/a15);
  a5=(a5*a26);
  a9=(a9-a5);
  a20=(a0*a20);
  a19=(a19*a20);
  a18=(a18*a19);
  a4=(a0*a4);
  a24=(a24*a4);
  a23=(a23*a24);
  a18=(a18-a23);
  a0=(a0*a8);
  a2=(a2*a0);
  a1=(a1*a2);
  a18=(a18+a1);
  a18=(a18/a15);
  a21=(a21/a15);
  a21=(a21*a6);
  a18=(a18-a21);
  a9=(a9+a18);
  a9=(-a9);
  if (res[0]!=0) res[0][7]=a9;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int tkad_G_dot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int tkad_G_dot_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int tkad_G_dot_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void tkad_G_dot_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int tkad_G_dot_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void tkad_G_dot_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void tkad_G_dot_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void tkad_G_dot_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int tkad_G_dot_n_in(void) { return 4;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int tkad_G_dot_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real tkad_G_dot_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* tkad_G_dot_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* tkad_G_dot_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* tkad_G_dot_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* tkad_G_dot_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int tkad_G_dot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


