/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int thd_phi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int thd_phi_alloc_mem(void);
extern "C" int thd_phi_init_mem(int mem);
extern "C" void thd_phi_free_mem(int mem);
extern "C" int thd_phi_checkout(void);
extern "C" void thd_phi_release(int mem);
extern "C" void thd_phi_incref(void);
extern "C" void thd_phi_decref(void);
extern "C" casadi_int thd_phi_n_in(void);
extern "C" casadi_int thd_phi_n_out(void);
extern "C" casadi_real thd_phi_default_in(casadi_int i);
extern "C" const char* thd_phi_name_in(casadi_int i);
extern "C" const char* thd_phi_name_out(casadi_int i);
extern "C" const casadi_int* thd_phi_sparsity_in(casadi_int i);
extern "C" const casadi_int* thd_phi_sparsity_out(casadi_int i);
extern "C" int thd_phi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define thd_phi_SZ_ARG 2
#define thd_phi_SZ_RES 1
#define thd_phi_SZ_IW 0
#define thd_phi_SZ_W 16
