/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int tkad_small_k(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int tkad_small_k_alloc_mem(void);
extern "C" int tkad_small_k_init_mem(int mem);
extern "C" void tkad_small_k_free_mem(int mem);
extern "C" int tkad_small_k_checkout(void);
extern "C" void tkad_small_k_release(int mem);
extern "C" void tkad_small_k_incref(void);
extern "C" void tkad_small_k_decref(void);
extern "C" casadi_int tkad_small_k_n_in(void);
extern "C" casadi_int tkad_small_k_n_out(void);
extern "C" casadi_real tkad_small_k_default_in(casadi_int i);
extern "C" const char* tkad_small_k_name_in(casadi_int i);
extern "C" const char* tkad_small_k_name_out(casadi_int i);
extern "C" const casadi_int* tkad_small_k_sparsity_in(casadi_int i);
extern "C" const casadi_int* tkad_small_k_sparsity_out(casadi_int i);
extern "C" int tkad_small_k_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define tkad_small_k_SZ_ARG 4
#define tkad_small_k_SZ_RES 1
#define tkad_small_k_SZ_IW 0
#define tkad_small_k_SZ_W 27
